version: '3.7'
services:
  api:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service api --api-tcp-port 8081 --node-id api
    ports:
      - "8081:8081"

  messages-1:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service messages -j api:3500 --initial-stream-config messages:1 --initial-stream-config events:1 --node-id messages-1
  messages-2:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service messages -j api:3500 --initial-stream-config messages:1 --initial-stream-config events:1 --node-id messages-2
  messages-3:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service messages -j api:3500 --initial-stream-config messages:1 --initial-stream-config events:1 --node-id messages-3

  kv-1:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service kv -j api:3500 --node-id kv-1
  kv-2:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service kv -j api:3500 --node-id kv-2
  kv-3:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service kv -j api:3500 --node-id kv-3

  queues-1:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service queues -j api:3500 --node-id queues-1
  queues-2:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service queues -j api:3500 --node-id queues-2
  queues-3:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service queues -j api:3500 --node-id queues-3

  sessions:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service sessions -j api:3500 --node-id sessions
  subscriptions:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service subscriptions -j api:3500 --node-id subscriptions
  router:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service router -j api:3500 --node-id router
  topics:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service topics -j api:3500 --node-id topics
  broker:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service broker -j api:3500 --node-id broker
  auth:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service auth -j api:3500 --node-id auth
  listener-1:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service listener -j api:3500 --node-id listener-1 --listener-tcp-port 1883
    ports:
      - "1883:1883"
  listener-2:
    build: { context: . }
    volumes: [ ./run_config:/run_config:ro ]
    command: service listener -j api:3500 --node-id listener-2 --listener-tcp-port 1884
    ports:
      - "1884:1884"
