// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package sessions is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Session
	SessionList
*/
package sessions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	ID                string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Tenant            string `protobuf:"bytes,2,opt,name=Tenant" json:"Tenant,omitempty"`
	Peer              string `protobuf:"bytes,3,opt,name=Peer" json:"Peer,omitempty"`
	WillTopic         []byte `protobuf:"bytes,4,opt,name=WillTopic,proto3" json:"WillTopic,omitempty"`
	WillQoS           int32  `protobuf:"varint,5,opt,name=WillQoS" json:"WillQoS,omitempty"`
	WillPayload       []byte `protobuf:"bytes,6,opt,name=WillPayload,proto3" json:"WillPayload,omitempty"`
	WillRetain        bool   `protobuf:"varint,7,opt,name=WillRetain" json:"WillRetain,omitempty"`
	Created           int64  `protobuf:"varint,8,opt,name=Created" json:"Created,omitempty"`
	ClientID          string `protobuf:"bytes,9,opt,name=ClientID" json:"ClientID,omitempty"`
	LastAdded         int64  `protobuf:"varint,10,opt,name=LastAdded" json:"LastAdded,omitempty"`
	LastDeleted       int64  `protobuf:"varint,11,opt,name=LastDeleted" json:"LastDeleted,omitempty"`
	Transport         string `protobuf:"bytes,12,opt,name=Transport" json:"Transport,omitempty"`
	RemoteAddress     string `protobuf:"bytes,13,opt,name=RemoteAddress" json:"RemoteAddress,omitempty"`
	ClosureReason     string `protobuf:"bytes,14,opt,name=ClosureReason" json:"ClosureReason,omitempty"`
	KeepaliveInterval int32  `protobuf:"varint,15,opt,name=KeepaliveInterval" json:"KeepaliveInterval,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Session) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Session) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Session) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *Session) GetWillTopic() []byte {
	if m != nil {
		return m.WillTopic
	}
	return nil
}

func (m *Session) GetWillQoS() int32 {
	if m != nil {
		return m.WillQoS
	}
	return 0
}

func (m *Session) GetWillPayload() []byte {
	if m != nil {
		return m.WillPayload
	}
	return nil
}

func (m *Session) GetWillRetain() bool {
	if m != nil {
		return m.WillRetain
	}
	return false
}

func (m *Session) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Session) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *Session) GetLastAdded() int64 {
	if m != nil {
		return m.LastAdded
	}
	return 0
}

func (m *Session) GetLastDeleted() int64 {
	if m != nil {
		return m.LastDeleted
	}
	return 0
}

func (m *Session) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

func (m *Session) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

func (m *Session) GetClosureReason() string {
	if m != nil {
		return m.ClosureReason
	}
	return ""
}

func (m *Session) GetKeepaliveInterval() int32 {
	if m != nil {
		return m.KeepaliveInterval
	}
	return 0
}

type SessionList struct {
	Sessions []*Session `protobuf:"bytes,1,rep,name=Sessions" json:"Sessions,omitempty"`
}

func (m *SessionList) Reset()                    { *m = SessionList{} }
func (m *SessionList) String() string            { return proto.CompactTextString(m) }
func (*SessionList) ProtoMessage()               {}
func (*SessionList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SessionList) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "sessions.Session")
	proto.RegisterType((*SessionList)(nil), "sessions.SessionList")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x3d, 0x6b, 0xf3, 0x30,
	0x10, 0xc7, 0x71, 0x9c, 0x17, 0xe7, 0x9c, 0xe4, 0x21, 0x1a, 0x1e, 0x8e, 0x52, 0x8a, 0x09, 0x1d,
	0x3c, 0xb4, 0x19, 0xda, 0xb5, 0x4b, 0x88, 0x17, 0xd3, 0x0c, 0xa9, 0x12, 0xe8, 0xac, 0xd6, 0x37,
	0x18, 0x54, 0xc9, 0x48, 0x6a, 0x20, 0x1f, 0xb2, 0xdf, 0xa9, 0x48, 0x71, 0xde, 0xe8, 0xa6, 0xdf,
	0xef, 0xfe, 0x77, 0x1c, 0x3e, 0x43, 0xea, 0xf6, 0x0d, 0xd9, 0x79, 0x63, 0xb4, 0xd3, 0x2c, 0xb1,
	0x64, 0x6d, 0xad, 0x95, 0x9d, 0xfd, 0xc4, 0x30, 0xd8, 0x1c, 0x80, 0x4d, 0xa0, 0x53, 0x16, 0x18,
	0x65, 0x51, 0x3e, 0xe4, 0x9d, 0xb2, 0x60, 0xff, 0xa1, 0xbf, 0x25, 0x25, 0x94, 0xc3, 0x4e, 0x70,
	0x2d, 0x31, 0x06, 0xdd, 0x35, 0x91, 0xc1, 0x38, 0xd8, 0xf0, 0x66, 0xb7, 0x30, 0x7c, 0xaf, 0xa5,
	0xdc, 0xea, 0xa6, 0xfe, 0xc4, 0x6e, 0x16, 0xe5, 0x23, 0x7e, 0x16, 0x0c, 0x61, 0xe0, 0xe1, 0x4d,
	0x6f, 0xb0, 0x97, 0x45, 0x79, 0x8f, 0x1f, 0x91, 0x65, 0x90, 0xfa, 0xe7, 0x5a, 0xec, 0xa5, 0x16,
	0x15, 0xf6, 0x43, 0xe7, 0xa5, 0x62, 0x77, 0x00, 0x1e, 0x39, 0x39, 0x51, 0x2b, 0x1c, 0x64, 0x51,
	0x9e, 0xf0, 0x0b, 0xe3, 0x67, 0x2f, 0x0d, 0x09, 0x47, 0x15, 0x26, 0x59, 0x94, 0xc7, 0xfc, 0x88,
	0xec, 0x06, 0x92, 0xa5, 0xac, 0x49, 0xb9, 0xb2, 0xc0, 0x61, 0xd8, 0xf5, 0xc4, 0x7e, 0xdf, 0x95,
	0xb0, 0x6e, 0x51, 0x55, 0x54, 0x21, 0x84, 0xbe, 0xb3, 0xf0, 0x5b, 0x79, 0x28, 0x48, 0x92, 0x9f,
	0x9b, 0x86, 0xfa, 0xa5, 0xf2, 0xfd, 0x5b, 0x23, 0x94, 0x6d, 0xb4, 0x71, 0x38, 0x0a, 0xc3, 0xcf,
	0x82, 0xdd, 0xc3, 0x98, 0xd3, 0x97, 0x76, 0xb4, 0xa8, 0x2a, 0x43, 0xd6, 0xe2, 0x38, 0x24, 0xae,
	0xa5, 0x4f, 0x2d, 0xa5, 0xb6, 0xdf, 0x86, 0x38, 0x09, 0xab, 0x15, 0x4e, 0x0e, 0xa9, 0x2b, 0xc9,
	0x1e, 0x60, 0xfa, 0x4a, 0xd4, 0x08, 0x59, 0xef, 0xa8, 0x54, 0x8e, 0xcc, 0x4e, 0x48, 0xfc, 0x17,
	0xbe, 0xe2, 0xdf, 0xc2, 0xec, 0x05, 0xd2, 0xf6, 0x9c, 0xab, 0xda, 0x3a, 0xf6, 0x08, 0x49, 0x8b,
	0x16, 0xa3, 0x2c, 0xce, 0xd3, 0xa7, 0xe9, 0xfc, 0x78, 0xfb, 0x79, 0x5b, 0xe1, 0xa7, 0xc8, 0x47,
	0x3f, 0xfc, 0x1e, 0xcf, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x17, 0x49, 0x66, 0x28, 0x2d, 0x02,
	0x00, 0x00,
}
