// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package sessions is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Session
	SessionList
*/
package sessions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	ID            string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Tenant        string `protobuf:"bytes,2,opt,name=Tenant" json:"Tenant,omitempty"`
	Peer          uint64 `protobuf:"varint,3,opt,name=Peer" json:"Peer,omitempty"`
	WillTopic     []byte `protobuf:"bytes,4,opt,name=WillTopic,proto3" json:"WillTopic,omitempty"`
	WillQoS       int32  `protobuf:"varint,5,opt,name=WillQoS" json:"WillQoS,omitempty"`
	WillPayload   []byte `protobuf:"bytes,6,opt,name=WillPayload,proto3" json:"WillPayload,omitempty"`
	WillRetain    bool   `protobuf:"varint,7,opt,name=WillRetain" json:"WillRetain,omitempty"`
	Created       int64  `protobuf:"varint,8,opt,name=Created" json:"Created,omitempty"`
	ClientID      []byte `protobuf:"bytes,9,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	LastAdded     int64  `protobuf:"varint,10,opt,name=LastAdded" json:"LastAdded,omitempty"`
	LastDeleted   int64  `protobuf:"varint,11,opt,name=LastDeleted" json:"LastDeleted,omitempty"`
	Transport     string `protobuf:"bytes,12,opt,name=Transport" json:"Transport,omitempty"`
	RemoteAddress string `protobuf:"bytes,13,opt,name=RemoteAddress" json:"RemoteAddress,omitempty"`
	ClosureReason string `protobuf:"bytes,14,opt,name=ClosureReason" json:"ClosureReason,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Session) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Session) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Session) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *Session) GetWillTopic() []byte {
	if m != nil {
		return m.WillTopic
	}
	return nil
}

func (m *Session) GetWillQoS() int32 {
	if m != nil {
		return m.WillQoS
	}
	return 0
}

func (m *Session) GetWillPayload() []byte {
	if m != nil {
		return m.WillPayload
	}
	return nil
}

func (m *Session) GetWillRetain() bool {
	if m != nil {
		return m.WillRetain
	}
	return false
}

func (m *Session) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Session) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *Session) GetLastAdded() int64 {
	if m != nil {
		return m.LastAdded
	}
	return 0
}

func (m *Session) GetLastDeleted() int64 {
	if m != nil {
		return m.LastDeleted
	}
	return 0
}

func (m *Session) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

func (m *Session) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

func (m *Session) GetClosureReason() string {
	if m != nil {
		return m.ClosureReason
	}
	return ""
}

type SessionList struct {
	Sessions []*Session `protobuf:"bytes,1,rep,name=Sessions" json:"Sessions,omitempty"`
}

func (m *SessionList) Reset()                    { *m = SessionList{} }
func (m *SessionList) String() string            { return proto.CompactTextString(m) }
func (*SessionList) ProtoMessage()               {}
func (*SessionList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SessionList) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "sessions.Session")
	proto.RegisterType((*SessionList)(nil), "sessions.SessionList")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x3d, 0x6b, 0xc3, 0x30,
	0x10, 0x86, 0x51, 0x9c, 0x0f, 0xe7, 0x9c, 0x04, 0xaa, 0xa1, 0x1c, 0xa5, 0x14, 0x11, 0x3a, 0x78,
	0x69, 0x86, 0x76, 0xed, 0x12, 0xe2, 0x25, 0x90, 0x21, 0x55, 0x02, 0x9d, 0xd5, 0xea, 0x06, 0x83,
	0x2b, 0x19, 0x49, 0x1d, 0xf2, 0x6b, 0xfa, 0x57, 0x8b, 0x14, 0xe7, 0x6b, 0xd3, 0xf3, 0xdc, 0x7b,
	0xc7, 0xa1, 0x83, 0x22, 0x1c, 0x5a, 0xf2, 0x8b, 0xd6, 0xd9, 0x60, 0x79, 0xee, 0xc9, 0xfb, 0xda,
	0x1a, 0x3f, 0xff, 0xcb, 0x60, 0xb4, 0x3b, 0x02, 0x9f, 0x41, 0x6f, 0x5d, 0x21, 0x13, 0xac, 0x1c,
	0xcb, 0xde, 0xba, 0xe2, 0xf7, 0x30, 0xdc, 0x93, 0x51, 0x26, 0x60, 0x2f, 0xb9, 0x8e, 0x38, 0x87,
	0xfe, 0x96, 0xc8, 0x61, 0x26, 0x58, 0xd9, 0x97, 0xe9, 0xcd, 0x1f, 0x61, 0xfc, 0x59, 0x37, 0xcd,
	0xde, 0xb6, 0xf5, 0x37, 0xf6, 0x05, 0x2b, 0x27, 0xf2, 0x22, 0x38, 0xc2, 0x28, 0xc2, 0x87, 0xdd,
	0xe1, 0x40, 0xb0, 0x72, 0x20, 0x4f, 0xc8, 0x05, 0x14, 0xf1, 0xb9, 0x55, 0x87, 0xc6, 0x2a, 0x8d,
	0xc3, 0xd4, 0x79, 0xad, 0xf8, 0x13, 0x40, 0x44, 0x49, 0x41, 0xd5, 0x06, 0x47, 0x82, 0x95, 0xb9,
	0xbc, 0x32, 0x71, 0xf6, 0xca, 0x91, 0x0a, 0xa4, 0x31, 0x17, 0xac, 0xcc, 0xe4, 0x09, 0xf9, 0x03,
	0xe4, 0xab, 0xa6, 0x26, 0x13, 0xd6, 0x15, 0x8e, 0xd3, 0xe0, 0x33, 0xc7, 0x7d, 0x37, 0xca, 0x87,
	0xa5, 0xd6, 0xa4, 0x11, 0x52, 0xdf, 0x45, 0xc4, 0xad, 0x22, 0x54, 0xd4, 0x50, 0x9c, 0x5b, 0xa4,
	0xfa, 0xb5, 0x8a, 0xfd, 0x7b, 0xa7, 0x8c, 0x6f, 0xad, 0x0b, 0x38, 0x49, 0xdf, 0x73, 0x11, 0xfc,
	0x19, 0xa6, 0x92, 0x7e, 0x6c, 0xa0, 0xa5, 0xd6, 0x8e, 0xbc, 0xc7, 0x69, 0x4a, 0xdc, 0xca, 0x98,
	0x5a, 0x35, 0xd6, 0xff, 0x3a, 0x92, 0xa4, 0xbc, 0x35, 0x38, 0x3b, 0xa6, 0x6e, 0xe4, 0xfc, 0x1d,
	0x8a, 0xee, 0x40, 0x9b, 0xda, 0x07, 0xfe, 0x02, 0x79, 0x87, 0x1e, 0x99, 0xc8, 0xca, 0xe2, 0xf5,
	0x6e, 0x71, 0xba, 0xe6, 0xa2, 0xab, 0xc8, 0x73, 0xe4, 0x6b, 0x98, 0x0e, 0xfe, 0xf6, 0x1f, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0x4f, 0xe3, 0x4b, 0xff, 0x01, 0x00, 0x00,
}
