// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package sessions is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Session
	SessionList
*/
package sessions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Session struct {
	ID          string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Tenant      string `protobuf:"bytes,2,opt,name=Tenant" json:"Tenant,omitempty"`
	Peer        uint64 `protobuf:"varint,3,opt,name=Peer" json:"Peer,omitempty"`
	WillTopic   []byte `protobuf:"bytes,4,opt,name=WillTopic,proto3" json:"WillTopic,omitempty"`
	WillQoS     int32  `protobuf:"varint,5,opt,name=WillQoS" json:"WillQoS,omitempty"`
	WillPayload []byte `protobuf:"bytes,6,opt,name=WillPayload,proto3" json:"WillPayload,omitempty"`
	WillRetain  bool   `protobuf:"varint,7,opt,name=WillRetain" json:"WillRetain,omitempty"`
	Created     int64  `protobuf:"varint,8,opt,name=Created" json:"Created,omitempty"`
	ClientID    []byte `protobuf:"bytes,9,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	LastAdded   int64  `protobuf:"varint,10,opt,name=LastAdded" json:"LastAdded,omitempty"`
	LastDeleted int64  `protobuf:"varint,11,opt,name=LastDeleted" json:"LastDeleted,omitempty"`
	Transport   string `protobuf:"bytes,12,opt,name=Transport" json:"Transport,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Session) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Session) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Session) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *Session) GetWillTopic() []byte {
	if m != nil {
		return m.WillTopic
	}
	return nil
}

func (m *Session) GetWillQoS() int32 {
	if m != nil {
		return m.WillQoS
	}
	return 0
}

func (m *Session) GetWillPayload() []byte {
	if m != nil {
		return m.WillPayload
	}
	return nil
}

func (m *Session) GetWillRetain() bool {
	if m != nil {
		return m.WillRetain
	}
	return false
}

func (m *Session) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Session) GetClientID() []byte {
	if m != nil {
		return m.ClientID
	}
	return nil
}

func (m *Session) GetLastAdded() int64 {
	if m != nil {
		return m.LastAdded
	}
	return 0
}

func (m *Session) GetLastDeleted() int64 {
	if m != nil {
		return m.LastDeleted
	}
	return 0
}

func (m *Session) GetTransport() string {
	if m != nil {
		return m.Transport
	}
	return ""
}

type SessionList struct {
	Sessions []*Session `protobuf:"bytes,1,rep,name=Sessions" json:"Sessions,omitempty"`
}

func (m *SessionList) Reset()                    { *m = SessionList{} }
func (m *SessionList) String() string            { return proto.CompactTextString(m) }
func (*SessionList) ProtoMessage()               {}
func (*SessionList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SessionList) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "sessions.Session")
	proto.RegisterType((*SessionList)(nil), "sessions.SessionList")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xbf, 0x6a, 0xc3, 0x30,
	0x10, 0x87, 0x91, 0xf3, 0xcf, 0x39, 0x87, 0x42, 0x35, 0x94, 0xa3, 0x94, 0x22, 0x32, 0x69, 0x69,
	0x86, 0x76, 0xed, 0x52, 0xe2, 0xc5, 0x90, 0x21, 0x55, 0x0c, 0x9d, 0xd5, 0xfa, 0x06, 0x81, 0x91,
	0x8c, 0xa5, 0x25, 0xcf, 0xd9, 0x17, 0x2a, 0x52, 0xed, 0xd8, 0x9b, 0xbe, 0xef, 0x74, 0x3f, 0x8e,
	0x3b, 0x28, 0xc2, 0xb5, 0x23, 0x7f, 0xe8, 0x7a, 0x17, 0x1c, 0xcf, 0x3d, 0x79, 0x6f, 0x9c, 0xf5,
	0xfb, 0xdf, 0x0c, 0x36, 0x97, 0x7f, 0xe0, 0x77, 0x90, 0x55, 0x25, 0x32, 0xc1, 0xe4, 0x56, 0x65,
	0x55, 0xc9, 0x1f, 0x60, 0x5d, 0x93, 0xd5, 0x36, 0x60, 0x96, 0xdc, 0x40, 0x9c, 0xc3, 0xf2, 0x4c,
	0xd4, 0xe3, 0x42, 0x30, 0xb9, 0x54, 0xe9, 0xcd, 0x9f, 0x60, 0xfb, 0x65, 0xda, 0xb6, 0x76, 0x9d,
	0xf9, 0xc1, 0xa5, 0x60, 0x72, 0xa7, 0x26, 0xc1, 0x11, 0x36, 0x11, 0x3e, 0xdd, 0x05, 0x57, 0x82,
	0xc9, 0x95, 0x1a, 0x91, 0x0b, 0x28, 0xe2, 0xf3, 0xac, 0xaf, 0xad, 0xd3, 0x0d, 0xae, 0x53, 0xe7,
	0x5c, 0xf1, 0x67, 0x80, 0x88, 0x8a, 0x82, 0x36, 0x16, 0x37, 0x82, 0xc9, 0x5c, 0xcd, 0x4c, 0xcc,
	0x3e, 0xf6, 0xa4, 0x03, 0x35, 0x98, 0x0b, 0x26, 0x17, 0x6a, 0x44, 0xfe, 0x08, 0xf9, 0xb1, 0x35,
	0x64, 0x43, 0x55, 0xe2, 0x36, 0x05, 0xdf, 0x38, 0xce, 0x7b, 0xd2, 0x3e, 0x7c, 0x34, 0x0d, 0x35,
	0x08, 0xa9, 0x6f, 0x12, 0x71, 0xaa, 0x08, 0x25, 0xb5, 0x14, 0x73, 0x8b, 0x54, 0x9f, 0xab, 0xd8,
	0x5f, 0xf7, 0xda, 0xfa, 0xce, 0xf5, 0x01, 0x77, 0x69, 0x3d, 0x93, 0xd8, 0xbf, 0x43, 0x31, 0x2c,
	0xf5, 0x64, 0x7c, 0xe0, 0x2f, 0x90, 0x0f, 0xe8, 0x91, 0x89, 0x85, 0x2c, 0x5e, 0xef, 0x0f, 0xe3,
	0x05, 0x0e, 0x43, 0x45, 0xdd, 0xbe, 0x7c, 0xaf, 0xd3, 0x91, 0xde, 0xfe, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x7e, 0x47, 0xc5, 0x0d, 0xb3, 0x01, 0x00, 0x00,
}
