// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package topics is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	RetainedMessage
*/
package topics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RetainedMessage struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Tenant  string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
	Topic   []byte `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos     int32  `protobuf:"varint,5,opt,name=qos" json:"qos,omitempty"`
}

func (m *RetainedMessage) Reset()                    { *m = RetainedMessage{} }
func (m *RetainedMessage) String() string            { return proto.CompactTextString(m) }
func (*RetainedMessage) ProtoMessage()               {}
func (*RetainedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RetainedMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RetainedMessage) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *RetainedMessage) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *RetainedMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RetainedMessage) GetQos() int32 {
	if m != nil {
		return m.Qos
	}
	return 0
}

func init() {
	proto.RegisterType((*RetainedMessage)(nil), "topics.RetainedMessage")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x31, 0x0a, 0x42, 0x31,
	0x0c, 0xc6, 0x71, 0xfa, 0x9e, 0xad, 0x18, 0x45, 0x25, 0x88, 0x64, 0x2c, 0x4e, 0x9d, 0x5c, 0x3c,
	0x87, 0x4b, 0x6f, 0x50, 0x6d, 0x90, 0x82, 0xb4, 0xd5, 0x66, 0x79, 0x78, 0x79, 0xb1, 0xea, 0x96,
	0xdf, 0x7f, 0x08, 0x1f, 0x2c, 0x65, 0xaa, 0xdc, 0x8e, 0xf5, 0x59, 0xa4, 0xa0, 0x91, 0x52, 0xd3,
	0xb5, 0x1d, 0x5e, 0xb0, 0xf1, 0x2c, 0x21, 0x65, 0x8e, 0x67, 0x6e, 0x2d, 0xdc, 0x18, 0xd7, 0x30,
	0xa4, 0x48, 0xca, 0x2a, 0xb7, 0xf0, 0x43, 0x8a, 0xb8, 0x07, 0x23, 0x9c, 0x43, 0x16, 0x1a, 0x7a,
	0xfb, 0x09, 0x77, 0xa0, 0xfb, 0x13, 0x1a, 0xad, 0x72, 0x2b, 0xff, 0x05, 0x12, 0xcc, 0x6b, 0x98,
	0xee, 0x25, 0x44, 0x9a, 0xf5, 0xfe, 0x27, 0x6e, 0x61, 0x7c, 0x94, 0x46, 0xda, 0x2a, 0xa7, 0xfd,
	0xe7, 0xbc, 0x98, 0xbe, 0xe5, 0xf4, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x38, 0x1f, 0x06, 0x9a,
	0x00, 0x00, 0x00,
}
