// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package topics is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	RetainedMessage
	RetainedMessageList
*/
package topics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RetainedMessage struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Tenant      string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
	Topic       []byte `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload     []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Qos         int32  `protobuf:"varint,5,opt,name=qos" json:"qos,omitempty"`
	LastUpdated int64  `protobuf:"varint,6,opt,name=LastUpdated" json:"LastUpdated,omitempty"`
	LastDeleted int64  `protobuf:"varint,7,opt,name=LastDeleted" json:"LastDeleted,omitempty"`
}

func (m *RetainedMessage) Reset()                    { *m = RetainedMessage{} }
func (m *RetainedMessage) String() string            { return proto.CompactTextString(m) }
func (*RetainedMessage) ProtoMessage()               {}
func (*RetainedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RetainedMessage) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RetainedMessage) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *RetainedMessage) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *RetainedMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RetainedMessage) GetQos() int32 {
	if m != nil {
		return m.Qos
	}
	return 0
}

func (m *RetainedMessage) GetLastUpdated() int64 {
	if m != nil {
		return m.LastUpdated
	}
	return 0
}

func (m *RetainedMessage) GetLastDeleted() int64 {
	if m != nil {
		return m.LastDeleted
	}
	return 0
}

type RetainedMessageList struct {
	RetainedMessages []*RetainedMessage `protobuf:"bytes,1,rep,name=RetainedMessages" json:"RetainedMessages,omitempty"`
}

func (m *RetainedMessageList) Reset()                    { *m = RetainedMessageList{} }
func (m *RetainedMessageList) String() string            { return proto.CompactTextString(m) }
func (*RetainedMessageList) ProtoMessage()               {}
func (*RetainedMessageList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RetainedMessageList) GetRetainedMessages() []*RetainedMessage {
	if m != nil {
		return m.RetainedMessages
	}
	return nil
}

func init() {
	proto.RegisterType((*RetainedMessage)(nil), "topics.RetainedMessage")
	proto.RegisterType((*RetainedMessageList)(nil), "topics.RetainedMessageList")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0xc9, 0xae, 0xbb, 0x87, 0xb3, 0xa2, 0xc7, 0x28, 0x3a, 0x65, 0xb8, 0x2a, 0xd5, 0x16,
	0xfa, 0x08, 0x5a, 0x9e, 0x4d, 0xc0, 0xc6, 0x2e, 0x9a, 0x41, 0x02, 0xc7, 0x26, 0x3a, 0xd3, 0xdc,
	0xd3, 0xf9, 0x6a, 0x72, 0xb9, 0x5b, 0x94, 0xb5, 0xcb, 0xff, 0xe5, 0x9b, 0x81, 0x7f, 0x60, 0xd0,
	0x7d, 0x61, 0x19, 0xcb, 0x57, 0xd6, 0x8c, 0xbd, 0xe6, 0x92, 0xde, 0x65, 0xf3, 0x6d, 0xe0, 0xca,
	0xb3, 0x86, 0x34, 0x71, 0x7c, 0x66, 0x91, 0xf0, 0xc1, 0x78, 0x09, 0x4d, 0x8a, 0x64, 0xac, 0x71,
	0xe7, 0xbe, 0x49, 0x11, 0x6f, 0xa1, 0x57, 0x9e, 0xc2, 0xa4, 0xd4, 0x54, 0x76, 0x4a, 0x78, 0x03,
	0x5d, 0xdd, 0x42, 0xad, 0x35, 0xee, 0xc2, 0x1f, 0x03, 0x12, 0xac, 0x4a, 0xd8, 0xef, 0x72, 0x88,
	0x74, 0x56, 0xf9, 0x1c, 0x71, 0x0d, 0xed, 0x67, 0x16, 0xea, 0xac, 0x71, 0x9d, 0x3f, 0x3c, 0xd1,
	0xc2, 0xb0, 0x0d, 0xa2, 0x2f, 0x25, 0x06, 0xe5, 0x48, 0xbd, 0x35, 0xae, 0xf5, 0x7f, 0xd1, 0x6c,
	0x3c, 0xf1, 0x8e, 0x0f, 0xc6, 0xea, 0xd7, 0x38, 0xa1, 0xcd, 0x2b, 0x5c, 0x2f, 0x0a, 0x6c, 0x93,
	0x28, 0x3e, 0xc2, 0x7a, 0x81, 0x85, 0x8c, 0x6d, 0xdd, 0x70, 0x7f, 0x37, 0x1e, 0xbb, 0x8f, 0x8b,
	0x7f, 0xff, 0x6f, 0xe0, 0xad, 0xaf, 0xc7, 0x7a, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0xad, 0x3f,
	0xf4, 0xcf, 0x3b, 0x01, 0x00, 0x00,
}
