// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransportContext struct {
	Encrypted            bool     `protobuf:"varint,1,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	RemoteAddress        string   `protobuf:"bytes,2,opt,name=remoteAddress,proto3" json:"remoteAddress,omitempty"`
	X509Certificate      []byte   `protobuf:"bytes,3,opt,name=x509Certificate,proto3" json:"x509Certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransportContext) Reset()         { *m = TransportContext{} }
func (m *TransportContext) String() string { return proto.CompactTextString(m) }
func (*TransportContext) ProtoMessage()    {}
func (*TransportContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *TransportContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportContext.Unmarshal(m, b)
}
func (m *TransportContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportContext.Marshal(b, m, deterministic)
}
func (m *TransportContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportContext.Merge(m, src)
}
func (m *TransportContext) XXX_Size() int {
	return xxx_messageInfo_TransportContext.Size(m)
}
func (m *TransportContext) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportContext.DiscardUnknown(m)
}

var xxx_messageInfo_TransportContext proto.InternalMessageInfo

func (m *TransportContext) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

func (m *TransportContext) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

func (m *TransportContext) GetX509Certificate() []byte {
	if m != nil {
		return m.X509Certificate
	}
	return nil
}

type ProtocolContext struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtocolContext) Reset()         { *m = ProtocolContext{} }
func (m *ProtocolContext) String() string { return proto.CompactTextString(m) }
func (*ProtocolContext) ProtoMessage()    {}
func (*ProtocolContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *ProtocolContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtocolContext.Unmarshal(m, b)
}
func (m *ProtocolContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtocolContext.Marshal(b, m, deterministic)
}
func (m *ProtocolContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtocolContext.Merge(m, src)
}
func (m *ProtocolContext) XXX_Size() int {
	return xxx_messageInfo_ProtocolContext.Size(m)
}
func (m *ProtocolContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtocolContext.DiscardUnknown(m)
}

var xxx_messageInfo_ProtocolContext proto.InternalMessageInfo

func (m *ProtocolContext) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProtocolContext) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateTokenInput struct {
	Protocol             *ProtocolContext  `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Transport            *TransportContext `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateTokenInput) Reset()         { *m = CreateTokenInput{} }
func (m *CreateTokenInput) String() string { return proto.CompactTextString(m) }
func (*CreateTokenInput) ProtoMessage()    {}
func (*CreateTokenInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *CreateTokenInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenInput.Unmarshal(m, b)
}
func (m *CreateTokenInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenInput.Marshal(b, m, deterministic)
}
func (m *CreateTokenInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenInput.Merge(m, src)
}
func (m *CreateTokenInput) XXX_Size() int {
	return xxx_messageInfo_CreateTokenInput.Size(m)
}
func (m *CreateTokenInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenInput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenInput proto.InternalMessageInfo

func (m *CreateTokenInput) GetProtocol() *ProtocolContext {
	if m != nil {
		return m.Protocol
	}
	return nil
}

func (m *CreateTokenInput) GetTransport() *TransportContext {
	if m != nil {
		return m.Transport
	}
	return nil
}

type CreateTokenOutput struct {
	JWT                  string   `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	EntityID             string   `protobuf:"bytes,3,opt,name=EntityID,proto3" json:"EntityID,omitempty"`
	SessionID            string   `protobuf:"bytes,4,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTokenOutput) Reset()         { *m = CreateTokenOutput{} }
func (m *CreateTokenOutput) String() string { return proto.CompactTextString(m) }
func (*CreateTokenOutput) ProtoMessage()    {}
func (*CreateTokenOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *CreateTokenOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenOutput.Unmarshal(m, b)
}
func (m *CreateTokenOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenOutput.Marshal(b, m, deterministic)
}
func (m *CreateTokenOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenOutput.Merge(m, src)
}
func (m *CreateTokenOutput) XXX_Size() int {
	return xxx_messageInfo_CreateTokenOutput.Size(m)
}
func (m *CreateTokenOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenOutput proto.InternalMessageInfo

func (m *CreateTokenOutput) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

func (m *CreateTokenOutput) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *CreateTokenOutput) GetEntityID() string {
	if m != nil {
		return m.EntityID
	}
	return ""
}

func (m *CreateTokenOutput) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

type Entity struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	AuthProvider         string   `protobuf:"bytes,3,opt,name=AuthProvider,proto3" json:"AuthProvider,omitempty"`
	Permissions          []string `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entity) Reset()         { *m = Entity{} }
func (m *Entity) String() string { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()    {}
func (*Entity) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *Entity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entity.Unmarshal(m, b)
}
func (m *Entity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entity.Marshal(b, m, deterministic)
}
func (m *Entity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entity.Merge(m, src)
}
func (m *Entity) XXX_Size() int {
	return xxx_messageInfo_Entity.Size(m)
}
func (m *Entity) XXX_DiscardUnknown() {
	xxx_messageInfo_Entity.DiscardUnknown(m)
}

var xxx_messageInfo_Entity proto.InternalMessageInfo

func (m *Entity) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Entity) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Entity) GetAuthProvider() string {
	if m != nil {
		return m.AuthProvider
	}
	return ""
}

func (m *Entity) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*TransportContext)(nil), "TransportContext")
	proto.RegisterType((*ProtocolContext)(nil), "ProtocolContext")
	proto.RegisterType((*CreateTokenInput)(nil), "CreateTokenInput")
	proto.RegisterType((*CreateTokenOutput)(nil), "CreateTokenOutput")
	proto.RegisterType((*Entity)(nil), "Entity")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0xef, 0x93, 0x40,
	0x10, 0xc5, 0x43, 0xfb, 0x4d, 0x03, 0x43, 0xb5, 0x74, 0x0f, 0x86, 0x34, 0x1e, 0x08, 0xf1, 0xc0,
	0xc1, 0xa0, 0xa9, 0x7a, 0xf0, 0xd8, 0x80, 0x07, 0xbc, 0xd8, 0x6c, 0x49, 0x3c, 0x53, 0x18, 0x23,
	0xd1, 0xee, 0xae, 0xbb, 0x43, 0x7f, 0xdc, 0xfc, 0xd3, 0x0d, 0x48, 0x69, 0x8b, 0xf1, 0xc6, 0x7b,
	0x3b, 0xcc, 0xe7, 0xed, 0x5b, 0xb0, 0xd5, 0x3e, 0x56, 0x5a, 0x92, 0x0c, 0x7f, 0x5b, 0xe0, 0xe5,
	0xba, 0x10, 0x46, 0x49, 0x4d, 0x89, 0x14, 0x84, 0x67, 0x62, 0x2f, 0xc1, 0x41, 0x51, 0xea, 0x8b,
	0x22, 0xac, 0x7c, 0x2b, 0xb0, 0x22, 0x9b, 0xdf, 0x0c, 0xf6, 0x0a, 0x9e, 0x69, 0x3c, 0x48, 0xc2,
	0x4d, 0x55, 0x69, 0x34, 0xc6, 0x9f, 0x04, 0x56, 0xe4, 0xf0, 0x47, 0x93, 0x45, 0xb0, 0x38, 0x7f,
	0x78, 0xfb, 0x31, 0x41, 0x4d, 0xf5, 0xb7, 0xba, 0x2c, 0x08, 0xfd, 0x69, 0x60, 0x45, 0x73, 0x3e,
	0xb6, 0xc3, 0x0c, 0x16, 0xdb, 0x36, 0x4b, 0x29, 0x7f, 0x5e, 0x03, 0xac, 0xc0, 0x6e, 0x0c, 0x6a,
	0x51, 0x1c, 0xb0, 0xe3, 0x3b, 0x7c, 0xd0, 0xed, 0x99, 0x2a, 0x8c, 0x39, 0x49, 0x5d, 0xf5, 0xe4,
	0x41, 0x87, 0xbf, 0xc0, 0x4b, 0x34, 0x16, 0x84, 0xb9, 0xfc, 0x81, 0x22, 0x13, 0xaa, 0x21, 0xf6,
	0x1a, 0x6c, 0xd5, 0xaf, 0xef, 0x76, 0xb9, 0x6b, 0x2f, 0x1e, 0xf1, 0xf8, 0x30, 0xc1, 0xde, 0x80,
	0x43, 0xd7, 0x3a, 0xba, 0xf5, 0xee, 0x7a, 0x19, 0x8f, 0x0b, 0xe2, 0xb7, 0x99, 0xf0, 0x04, 0xcb,
	0x3b, 0xe4, 0x97, 0x86, 0x5a, 0xa6, 0x07, 0xd3, 0xcf, 0x5f, 0xf3, 0x3e, 0x7a, 0xfb, 0xc9, 0x5e,
	0xc0, 0x2c, 0x47, 0x51, 0x08, 0xea, 0x33, 0xf7, 0xaa, 0xbd, 0xcd, 0x27, 0x41, 0x35, 0x5d, 0xb2,
	0xb4, 0xeb, 0xc7, 0xe1, 0x83, 0x6e, 0x9f, 0x61, 0x87, 0xc6, 0xd4, 0x52, 0x64, 0xa9, 0xff, 0xd4,
	0x1d, 0xde, 0x8c, 0xf0, 0x08, 0xb3, 0xbf, 0x93, 0xec, 0x39, 0x4c, 0xb2, 0xb4, 0x87, 0x4d, 0xb2,
	0xf4, 0xbf, 0xac, 0x10, 0xe6, 0x9b, 0x86, 0xbe, 0x6f, 0xb5, 0x3c, 0xd6, 0x15, 0xea, 0x9e, 0xf7,
	0xe0, 0xb1, 0x00, 0x5c, 0x85, 0xfa, 0x50, 0x77, 0x14, 0xe3, 0x3f, 0x05, 0xd3, 0xc8, 0xe1, 0xf7,
	0xd6, 0x3a, 0x01, 0xb7, 0xfd, 0x63, 0x87, 0xfa, 0x58, 0x97, 0xc8, 0xde, 0x83, 0x7b, 0x77, 0x7f,
	0xb6, 0x8c, 0xc7, 0x0f, 0xb0, 0x62, 0xf1, 0x3f, 0x05, 0xed, 0x67, 0x5d, 0xe1, 0xef, 0xfe, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x97, 0xa2, 0xe3, 0x0e, 0x89, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	CreateToken(ctx context.Context, in *CreateTokenInput, opts ...grpc.CallOption) (*CreateTokenOutput, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) CreateToken(ctx context.Context, in *CreateTokenInput, opts ...grpc.CallOption) (*CreateTokenOutput, error) {
	out := new(CreateTokenOutput)
	err := c.cc.Invoke(ctx, "/AuthService/CreateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	CreateToken(context.Context, *CreateTokenInput) (*CreateTokenOutput, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) CreateToken(ctx context.Context, req *CreateTokenInput) (*CreateTokenOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTokenInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/CreateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateToken(ctx, req.(*CreateTokenInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateToken",
			Handler:    _AuthService_CreateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}
