// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	sessions "github.com/vx-labs/mqtt-broker/sessions"
	_ "github.com/vx-labs/mqtt-broker/subscriptions"
	_ "github.com/vx-labs/mqtt-broker/topics"
	packet "github.com/vx-labs/mqtt-protocol/packet"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionFilter struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionFilter) Reset()         { *m = SessionFilter{} }
func (m *SessionFilter) String() string { return proto.CompactTextString(m) }
func (*SessionFilter) ProtoMessage()    {}
func (*SessionFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *SessionFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionFilter.Unmarshal(m, b)
}
func (m *SessionFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionFilter.Marshal(b, m, deterministic)
}
func (m *SessionFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionFilter.Merge(m, src)
}
func (m *SessionFilter) XXX_Size() int {
	return xxx_messageInfo_SessionFilter.Size(m)
}
func (m *SessionFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionFilter.DiscardUnknown(m)
}

var xxx_messageInfo_SessionFilter proto.InternalMessageInfo

type CloseSessionInput struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseSessionInput) Reset()         { *m = CloseSessionInput{} }
func (m *CloseSessionInput) String() string { return proto.CompactTextString(m) }
func (*CloseSessionInput) ProtoMessage()    {}
func (*CloseSessionInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *CloseSessionInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseSessionInput.Unmarshal(m, b)
}
func (m *CloseSessionInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseSessionInput.Marshal(b, m, deterministic)
}
func (m *CloseSessionInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseSessionInput.Merge(m, src)
}
func (m *CloseSessionInput) XXX_Size() int {
	return xxx_messageInfo_CloseSessionInput.Size(m)
}
func (m *CloseSessionInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseSessionInput.DiscardUnknown(m)
}

var xxx_messageInfo_CloseSessionInput proto.InternalMessageInfo

func (m *CloseSessionInput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type CloseSessionOutput struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseSessionOutput) Reset()         { *m = CloseSessionOutput{} }
func (m *CloseSessionOutput) String() string { return proto.CompactTextString(m) }
func (*CloseSessionOutput) ProtoMessage()    {}
func (*CloseSessionOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *CloseSessionOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseSessionOutput.Unmarshal(m, b)
}
func (m *CloseSessionOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseSessionOutput.Marshal(b, m, deterministic)
}
func (m *CloseSessionOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseSessionOutput.Merge(m, src)
}
func (m *CloseSessionOutput) XXX_Size() int {
	return xxx_messageInfo_CloseSessionOutput.Size(m)
}
func (m *CloseSessionOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseSessionOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CloseSessionOutput proto.InternalMessageInfo

func (m *CloseSessionOutput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ListSessionsOutput struct {
	Sessions             []*sessions.Metadata `protobuf:"bytes,1,rep,name=Sessions,proto3" json:"Sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListSessionsOutput) Reset()         { *m = ListSessionsOutput{} }
func (m *ListSessionsOutput) String() string { return proto.CompactTextString(m) }
func (*ListSessionsOutput) ProtoMessage()    {}
func (*ListSessionsOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *ListSessionsOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSessionsOutput.Unmarshal(m, b)
}
func (m *ListSessionsOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSessionsOutput.Marshal(b, m, deterministic)
}
func (m *ListSessionsOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSessionsOutput.Merge(m, src)
}
func (m *ListSessionsOutput) XXX_Size() int {
	return xxx_messageInfo_ListSessionsOutput.Size(m)
}
func (m *ListSessionsOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSessionsOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ListSessionsOutput proto.InternalMessageInfo

func (m *ListSessionsOutput) GetSessions() []*sessions.Metadata {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type MessagePublished struct {
	Recipient            string   `protobuf:"bytes,1,opt,name=Recipient,proto3" json:"Recipient,omitempty"`
	Topic                []byte   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Qos                  int32    `protobuf:"varint,3,opt,name=Qos,proto3" json:"Qos,omitempty"`
	Payload              []byte   `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Retained             bool     `protobuf:"varint,5,opt,name=Retained,proto3" json:"Retained,omitempty"`
	Dup                  bool     `protobuf:"varint,6,opt,name=Dup,proto3" json:"Dup,omitempty"`
	Tenant               string   `protobuf:"bytes,7,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagePublished) Reset()         { *m = MessagePublished{} }
func (m *MessagePublished) String() string { return proto.CompactTextString(m) }
func (*MessagePublished) ProtoMessage()    {}
func (*MessagePublished) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *MessagePublished) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePublished.Unmarshal(m, b)
}
func (m *MessagePublished) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePublished.Marshal(b, m, deterministic)
}
func (m *MessagePublished) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePublished.Merge(m, src)
}
func (m *MessagePublished) XXX_Size() int {
	return xxx_messageInfo_MessagePublished.Size(m)
}
func (m *MessagePublished) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePublished.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePublished proto.InternalMessageInfo

func (m *MessagePublished) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MessagePublished) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *MessagePublished) GetQos() int32 {
	if m != nil {
		return m.Qos
	}
	return 0
}

func (m *MessagePublished) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MessagePublished) GetRetained() bool {
	if m != nil {
		return m.Retained
	}
	return false
}

func (m *MessagePublished) GetDup() bool {
	if m != nil {
		return m.Dup
	}
	return false
}

func (m *MessagePublished) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type MessagePublishedOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagePublishedOutput) Reset()         { *m = MessagePublishedOutput{} }
func (m *MessagePublishedOutput) String() string { return proto.CompactTextString(m) }
func (*MessagePublishedOutput) ProtoMessage()    {}
func (*MessagePublishedOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *MessagePublishedOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagePublishedOutput.Unmarshal(m, b)
}
func (m *MessagePublishedOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagePublishedOutput.Marshal(b, m, deterministic)
}
func (m *MessagePublishedOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagePublishedOutput.Merge(m, src)
}
func (m *MessagePublishedOutput) XXX_Size() int {
	return xxx_messageInfo_MessagePublishedOutput.Size(m)
}
func (m *MessagePublishedOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagePublishedOutput.DiscardUnknown(m)
}

var xxx_messageInfo_MessagePublishedOutput proto.InternalMessageInfo

type TransportMetadata struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Encrypted            bool     `protobuf:"varint,2,opt,name=Encrypted,proto3" json:"Encrypted,omitempty"`
	RemoteAddress        string   `protobuf:"bytes,3,opt,name=RemoteAddress,proto3" json:"RemoteAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransportMetadata) Reset()         { *m = TransportMetadata{} }
func (m *TransportMetadata) String() string { return proto.CompactTextString(m) }
func (*TransportMetadata) ProtoMessage()    {}
func (*TransportMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *TransportMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransportMetadata.Unmarshal(m, b)
}
func (m *TransportMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransportMetadata.Marshal(b, m, deterministic)
}
func (m *TransportMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransportMetadata.Merge(m, src)
}
func (m *TransportMetadata) XXX_Size() int {
	return xxx_messageInfo_TransportMetadata.Size(m)
}
func (m *TransportMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_TransportMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_TransportMetadata proto.InternalMessageInfo

func (m *TransportMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TransportMetadata) GetEncrypted() bool {
	if m != nil {
		return m.Encrypted
	}
	return false
}

func (m *TransportMetadata) GetRemoteAddress() string {
	if m != nil {
		return m.RemoteAddress
	}
	return ""
}

type ConnectInput struct {
	TransportMetadata    *TransportMetadata `protobuf:"bytes,1,opt,name=TransportMetadata,proto3" json:"TransportMetadata,omitempty"`
	Connect              *packet.Connect    `protobuf:"bytes,2,opt,name=Connect,proto3" json:"Connect,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ConnectInput) Reset()         { *m = ConnectInput{} }
func (m *ConnectInput) String() string { return proto.CompactTextString(m) }
func (*ConnectInput) ProtoMessage()    {}
func (*ConnectInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *ConnectInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectInput.Unmarshal(m, b)
}
func (m *ConnectInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectInput.Marshal(b, m, deterministic)
}
func (m *ConnectInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectInput.Merge(m, src)
}
func (m *ConnectInput) XXX_Size() int {
	return xxx_messageInfo_ConnectInput.Size(m)
}
func (m *ConnectInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectInput.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectInput proto.InternalMessageInfo

func (m *ConnectInput) GetTransportMetadata() *TransportMetadata {
	if m != nil {
		return m.TransportMetadata
	}
	return nil
}

func (m *ConnectInput) GetConnect() *packet.Connect {
	if m != nil {
		return m.Connect
	}
	return nil
}

type ConnectOutput struct {
	ID                   string          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ConnAck              *packet.ConnAck `protobuf:"bytes,2,opt,name=ConnAck,proto3" json:"ConnAck,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ConnectOutput) Reset()         { *m = ConnectOutput{} }
func (m *ConnectOutput) String() string { return proto.CompactTextString(m) }
func (*ConnectOutput) ProtoMessage()    {}
func (*ConnectOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *ConnectOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectOutput.Unmarshal(m, b)
}
func (m *ConnectOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectOutput.Marshal(b, m, deterministic)
}
func (m *ConnectOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectOutput.Merge(m, src)
}
func (m *ConnectOutput) XXX_Size() int {
	return xxx_messageInfo_ConnectOutput.Size(m)
}
func (m *ConnectOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectOutput.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectOutput proto.InternalMessageInfo

func (m *ConnectOutput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ConnectOutput) GetConnAck() *packet.ConnAck {
	if m != nil {
		return m.ConnAck
	}
	return nil
}

type DisconnectInput struct {
	ID                   string             `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Disconnect           *packet.Disconnect `protobuf:"bytes,2,opt,name=Disconnect,proto3" json:"Disconnect,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DisconnectInput) Reset()         { *m = DisconnectInput{} }
func (m *DisconnectInput) String() string { return proto.CompactTextString(m) }
func (*DisconnectInput) ProtoMessage()    {}
func (*DisconnectInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *DisconnectInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectInput.Unmarshal(m, b)
}
func (m *DisconnectInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectInput.Marshal(b, m, deterministic)
}
func (m *DisconnectInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectInput.Merge(m, src)
}
func (m *DisconnectInput) XXX_Size() int {
	return xxx_messageInfo_DisconnectInput.Size(m)
}
func (m *DisconnectInput) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectInput.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectInput proto.InternalMessageInfo

func (m *DisconnectInput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DisconnectInput) GetDisconnect() *packet.Disconnect {
	if m != nil {
		return m.Disconnect
	}
	return nil
}

type DisconnectOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisconnectOutput) Reset()         { *m = DisconnectOutput{} }
func (m *DisconnectOutput) String() string { return proto.CompactTextString(m) }
func (*DisconnectOutput) ProtoMessage()    {}
func (*DisconnectOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *DisconnectOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisconnectOutput.Unmarshal(m, b)
}
func (m *DisconnectOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisconnectOutput.Marshal(b, m, deterministic)
}
func (m *DisconnectOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisconnectOutput.Merge(m, src)
}
func (m *DisconnectOutput) XXX_Size() int {
	return xxx_messageInfo_DisconnectOutput.Size(m)
}
func (m *DisconnectOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_DisconnectOutput.DiscardUnknown(m)
}

var xxx_messageInfo_DisconnectOutput proto.InternalMessageInfo

type PublishInput struct {
	ID                   string          `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Publish              *packet.Publish `protobuf:"bytes,2,opt,name=Publish,proto3" json:"Publish,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PublishInput) Reset()         { *m = PublishInput{} }
func (m *PublishInput) String() string { return proto.CompactTextString(m) }
func (*PublishInput) ProtoMessage()    {}
func (*PublishInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *PublishInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishInput.Unmarshal(m, b)
}
func (m *PublishInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishInput.Marshal(b, m, deterministic)
}
func (m *PublishInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishInput.Merge(m, src)
}
func (m *PublishInput) XXX_Size() int {
	return xxx_messageInfo_PublishInput.Size(m)
}
func (m *PublishInput) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishInput.DiscardUnknown(m)
}

var xxx_messageInfo_PublishInput proto.InternalMessageInfo

func (m *PublishInput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *PublishInput) GetPublish() *packet.Publish {
	if m != nil {
		return m.Publish
	}
	return nil
}

type PublishOutput struct {
	PubAck               *packet.PubAck `protobuf:"bytes,1,opt,name=PubAck,proto3" json:"PubAck,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PublishOutput) Reset()         { *m = PublishOutput{} }
func (m *PublishOutput) String() string { return proto.CompactTextString(m) }
func (*PublishOutput) ProtoMessage()    {}
func (*PublishOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *PublishOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishOutput.Unmarshal(m, b)
}
func (m *PublishOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishOutput.Marshal(b, m, deterministic)
}
func (m *PublishOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishOutput.Merge(m, src)
}
func (m *PublishOutput) XXX_Size() int {
	return xxx_messageInfo_PublishOutput.Size(m)
}
func (m *PublishOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishOutput.DiscardUnknown(m)
}

var xxx_messageInfo_PublishOutput proto.InternalMessageInfo

func (m *PublishOutput) GetPubAck() *packet.PubAck {
	if m != nil {
		return m.PubAck
	}
	return nil
}

type SubscribeInput struct {
	ID                   string            `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Subscribe            *packet.Subscribe `protobuf:"bytes,2,opt,name=Subscribe,proto3" json:"Subscribe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SubscribeInput) Reset()         { *m = SubscribeInput{} }
func (m *SubscribeInput) String() string { return proto.CompactTextString(m) }
func (*SubscribeInput) ProtoMessage()    {}
func (*SubscribeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *SubscribeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeInput.Unmarshal(m, b)
}
func (m *SubscribeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeInput.Marshal(b, m, deterministic)
}
func (m *SubscribeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeInput.Merge(m, src)
}
func (m *SubscribeInput) XXX_Size() int {
	return xxx_messageInfo_SubscribeInput.Size(m)
}
func (m *SubscribeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeInput.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeInput proto.InternalMessageInfo

func (m *SubscribeInput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SubscribeInput) GetSubscribe() *packet.Subscribe {
	if m != nil {
		return m.Subscribe
	}
	return nil
}

type SubscribeOutput struct {
	SubAck               *packet.SubAck `protobuf:"bytes,1,opt,name=SubAck,proto3" json:"SubAck,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SubscribeOutput) Reset()         { *m = SubscribeOutput{} }
func (m *SubscribeOutput) String() string { return proto.CompactTextString(m) }
func (*SubscribeOutput) ProtoMessage()    {}
func (*SubscribeOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{14}
}

func (m *SubscribeOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeOutput.Unmarshal(m, b)
}
func (m *SubscribeOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeOutput.Marshal(b, m, deterministic)
}
func (m *SubscribeOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeOutput.Merge(m, src)
}
func (m *SubscribeOutput) XXX_Size() int {
	return xxx_messageInfo_SubscribeOutput.Size(m)
}
func (m *SubscribeOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeOutput proto.InternalMessageInfo

func (m *SubscribeOutput) GetSubAck() *packet.SubAck {
	if m != nil {
		return m.SubAck
	}
	return nil
}

type UnsubscribeInput struct {
	ID                   string              `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Unsubscribe          *packet.Unsubscribe `protobuf:"bytes,2,opt,name=Unsubscribe,proto3" json:"Unsubscribe,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *UnsubscribeInput) Reset()         { *m = UnsubscribeInput{} }
func (m *UnsubscribeInput) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeInput) ProtoMessage()    {}
func (*UnsubscribeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{15}
}

func (m *UnsubscribeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeInput.Unmarshal(m, b)
}
func (m *UnsubscribeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeInput.Marshal(b, m, deterministic)
}
func (m *UnsubscribeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeInput.Merge(m, src)
}
func (m *UnsubscribeInput) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeInput.Size(m)
}
func (m *UnsubscribeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeInput.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeInput proto.InternalMessageInfo

func (m *UnsubscribeInput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UnsubscribeInput) GetUnsubscribe() *packet.Unsubscribe {
	if m != nil {
		return m.Unsubscribe
	}
	return nil
}

type UnsubscribeOutput struct {
	UnsubAck             *packet.UnsubAck `protobuf:"bytes,1,opt,name=UnsubAck,proto3" json:"UnsubAck,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UnsubscribeOutput) Reset()         { *m = UnsubscribeOutput{} }
func (m *UnsubscribeOutput) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeOutput) ProtoMessage()    {}
func (*UnsubscribeOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{16}
}

func (m *UnsubscribeOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeOutput.Unmarshal(m, b)
}
func (m *UnsubscribeOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeOutput.Marshal(b, m, deterministic)
}
func (m *UnsubscribeOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeOutput.Merge(m, src)
}
func (m *UnsubscribeOutput) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeOutput.Size(m)
}
func (m *UnsubscribeOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeOutput.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeOutput proto.InternalMessageInfo

func (m *UnsubscribeOutput) GetUnsubAck() *packet.UnsubAck {
	if m != nil {
		return m.UnsubAck
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionFilter)(nil), "SessionFilter")
	proto.RegisterType((*CloseSessionInput)(nil), "CloseSessionInput")
	proto.RegisterType((*CloseSessionOutput)(nil), "CloseSessionOutput")
	proto.RegisterType((*ListSessionsOutput)(nil), "ListSessionsOutput")
	proto.RegisterType((*MessagePublished)(nil), "MessagePublished")
	proto.RegisterType((*MessagePublishedOutput)(nil), "MessagePublishedOutput")
	proto.RegisterType((*TransportMetadata)(nil), "TransportMetadata")
	proto.RegisterType((*ConnectInput)(nil), "ConnectInput")
	proto.RegisterType((*ConnectOutput)(nil), "ConnectOutput")
	proto.RegisterType((*DisconnectInput)(nil), "DisconnectInput")
	proto.RegisterType((*DisconnectOutput)(nil), "DisconnectOutput")
	proto.RegisterType((*PublishInput)(nil), "PublishInput")
	proto.RegisterType((*PublishOutput)(nil), "PublishOutput")
	proto.RegisterType((*SubscribeInput)(nil), "SubscribeInput")
	proto.RegisterType((*SubscribeOutput)(nil), "SubscribeOutput")
	proto.RegisterType((*UnsubscribeInput)(nil), "UnsubscribeInput")
	proto.RegisterType((*UnsubscribeOutput)(nil), "UnsubscribeOutput")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 749 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x55, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x56, 0x9a, 0x36, 0x3f, 0xd3, 0xfc, 0x79, 0x7b, 0xd4, 0x63, 0x59, 0xe7, 0x22, 0xda, 0x53,
	0x1d, 0xa5, 0xd2, 0xe9, 0x86, 0xa6, 0xa0, 0xc2, 0x15, 0x84, 0x06, 0xa4, 0x20, 0x0a, 0xed, 0xa6,
	0xbd, 0xe0, 0xd2, 0x76, 0x56, 0xad, 0x95, 0xc4, 0x36, 0xde, 0x75, 0x45, 0xc5, 0x23, 0xf1, 0x02,
	0x3c, 0x1e, 0xb2, 0xbd, 0xb6, 0xd7, 0x8e, 0xa1, 0x57, 0xd9, 0x99, 0xf9, 0xe6, 0xdb, 0x6f, 0x3c,
	0xb3, 0x13, 0x68, 0x07, 0xbe, 0x4d, 0xfc, 0xc0, 0x13, 0x9e, 0x71, 0x7a, 0xe7, 0x88, 0xfb, 0xd0,
	0x22, 0xb6, 0xb7, 0x19, 0x3f, 0x7c, 0x3b, 0x59, 0x9b, 0x16, 0x1f, 0x6f, 0xbe, 0x0a, 0x71, 0x62,
	0x05, 0xde, 0x8a, 0x05, 0x63, 0xe1, 0xf9, 0x8e, 0xcd, 0xc7, 0xe2, 0xd1, 0x67, 0x5c, 0xa6, 0xbc,
	0x7c, 0x22, 0x85, 0x87, 0x16, 0xb7, 0x03, 0xc7, 0x17, 0x8e, 0xe7, 0x16, 0x33, 0xcf, 0x9e, 0xca,
	0x64, 0x9c, 0x6f, 0x25, 0x3d, 0xfb, 0x5d, 0x52, 0x1c, 0xb6, 0xbd, 0xf5, 0xd8, 0x37, 0xed, 0x15,
	0x13, 0x63, 0xdf, 0x4a, 0x32, 0x70, 0x1f, 0xba, 0x8b, 0x84, 0xe9, 0xbd, 0xb3, 0x16, 0x2c, 0xc0,
	0xff, 0x82, 0x76, 0xb1, 0xf6, 0x38, 0x93, 0xde, 0xb9, 0xeb, 0x87, 0x02, 0xf5, 0x60, 0x67, 0x3e,
	0xd3, 0x6b, 0xc3, 0xda, 0xa8, 0x4d, 0x77, 0xe6, 0x33, 0x7c, 0x04, 0x48, 0x05, 0x7d, 0x0e, 0x45,
	0x15, 0x6a, 0x06, 0xe8, 0xa3, 0xc3, 0x85, 0x04, 0x71, 0x89, 0x22, 0xd0, 0x4a, 0x3d, 0x7a, 0x6d,
	0x58, 0x1f, 0xed, 0x4f, 0x10, 0x49, 0x8b, 0x21, 0x97, 0x4c, 0x98, 0x4b, 0x53, 0x98, 0x34, 0xc3,
	0xe0, 0x9f, 0x35, 0x18, 0x5c, 0x32, 0xce, 0xcd, 0x3b, 0x76, 0x15, 0x5a, 0x6b, 0x87, 0xdf, 0xb3,
	0x25, 0xfa, 0x07, 0xda, 0x94, 0xd9, 0x8e, 0xef, 0x30, 0x57, 0xc8, 0x1b, 0x73, 0x07, 0xfa, 0x0b,
	0xf6, 0x6e, 0xa2, 0x5e, 0xe8, 0x3b, 0xc3, 0xda, 0xa8, 0x43, 0x13, 0x03, 0x0d, 0xa0, 0x7e, 0xed,
	0x71, 0xbd, 0x3e, 0xac, 0x8d, 0xf6, 0x68, 0x74, 0x44, 0x3a, 0x34, 0xaf, 0xcc, 0xc7, 0xb5, 0x67,
	0x2e, 0xf5, 0xdd, 0x18, 0x99, 0x9a, 0xc8, 0x80, 0x16, 0x65, 0xc2, 0x74, 0x5c, 0xb6, 0xd4, 0xf7,
	0x86, 0xb5, 0x51, 0x8b, 0x66, 0x76, 0xc4, 0x33, 0x0b, 0x7d, 0xbd, 0x11, 0xbb, 0xa3, 0x23, 0x3a,
	0x84, 0xc6, 0x0d, 0x73, 0x4d, 0x57, 0xe8, 0xcd, 0x58, 0x8a, 0xb4, 0xb0, 0x0e, 0x87, 0x65, 0xe5,
	0xc9, 0x47, 0xc0, 0x2b, 0xd0, 0x6e, 0x02, 0xd3, 0xe5, 0xbe, 0x17, 0x88, 0xb4, 0x66, 0x84, 0x60,
	0xf7, 0x93, 0xb9, 0x61, 0xb2, 0x9e, 0xf8, 0x1c, 0x15, 0xfa, 0xce, 0xb5, 0x83, 0x47, 0x5f, 0xb0,
	0x65, 0x5c, 0x4e, 0x8b, 0xe6, 0x0e, 0x74, 0x04, 0x5d, 0xca, 0x36, 0x9e, 0x60, 0xd3, 0xe5, 0x32,
	0x60, 0x3c, 0x29, 0xae, 0x4d, 0x8b, 0x4e, 0xfc, 0x1d, 0x3a, 0x17, 0x9e, 0xeb, 0x32, 0x5b, 0x24,
	0xdd, 0x7c, 0x53, 0x71, 0x79, 0x7c, 0x69, 0xd4, 0x8a, 0xad, 0x08, 0xad, 0x50, 0x7a, 0x0c, 0x4d,
	0xc9, 0x18, 0x6b, 0xda, 0x9f, 0xf4, 0x49, 0x32, 0x58, 0x44, 0xba, 0x69, 0x1a, 0xc7, 0x1f, 0xa0,
	0x2b, 0x8f, 0xd5, 0x53, 0x92, 0x72, 0x4d, 0xed, 0x55, 0x15, 0xd7, 0xd4, 0x5e, 0xd1, 0x34, 0x8e,
	0x6f, 0xa1, 0x3f, 0x73, 0xb8, 0xad, 0xd6, 0x52, 0x66, 0x9b, 0x00, 0xe4, 0x10, 0x49, 0x88, 0x52,
	0xc2, 0x3c, 0x42, 0x15, 0x14, 0x46, 0x30, 0xc8, 0x2d, 0xd9, 0xa0, 0x39, 0x74, 0x64, 0xcf, 0xaa,
	0xef, 0x39, 0x86, 0xa6, 0x8c, 0x97, 0x55, 0x4b, 0x37, 0x4d, 0xe3, 0xf8, 0x1c, 0xba, 0xf2, 0x28,
	0xbf, 0xc0, 0x7f, 0xd0, 0xb8, 0x0a, 0xad, 0xa8, 0xe0, 0xe4, 0xa3, 0xf7, 0x94, 0xd4, 0xa8, 0x5e,
	0x19, 0xc5, 0xd7, 0xd0, 0x5b, 0x24, 0xfb, 0xc1, 0x62, 0xd5, 0x2a, 0xc6, 0xd0, 0xce, 0x10, 0x52,
	0x87, 0x96, 0x92, 0x65, 0x01, 0x9a, 0x63, 0xf0, 0x2b, 0xe8, 0x67, 0x46, 0xae, 0x66, 0x51, 0xa9,
	0x66, 0x21, 0xd5, 0x24, 0xbf, 0xf8, 0x0b, 0x0c, 0x6e, 0x5d, 0xfe, 0x67, 0x3d, 0x2f, 0x60, 0x5f,
	0xc1, 0x48, 0x45, 0x07, 0x29, 0xa1, 0x12, 0xa2, 0x2a, 0x0e, 0x4f, 0x41, 0x53, 0x4c, 0xa9, 0xeb,
	0x7f, 0x68, 0xc5, 0xce, 0x5c, 0xd9, 0xa0, 0x40, 0x14, 0x69, 0xcb, 0x10, 0x93, 0x1f, 0x75, 0xe8,
	0xbe, 0x8d, 0x37, 0xe3, 0x82, 0x05, 0x0f, 0x8e, 0xcd, 0xd0, 0x19, 0x74, 0xd4, 0xed, 0x83, 0x7a,
	0xa4, 0xb0, 0xe8, 0x8c, 0x03, 0x52, 0xb1, 0x9c, 0xce, 0xa1, 0xa3, 0x2e, 0x36, 0x84, 0xc8, 0xd6,
	0x32, 0x34, 0x0e, 0x48, 0xc5, 0xee, 0x7b, 0x0d, 0xda, 0xcc, 0xe1, 0x22, 0x70, 0xac, 0x50, 0x30,
	0xf9, 0xe8, 0x91, 0x46, 0xca, 0xcf, 0xdf, 0xf8, 0x9b, 0x54, 0x6f, 0x04, 0x34, 0xca, 0x9e, 0x14,
	0xea, 0x12, 0xf5, 0xb9, 0x1a, 0x3d, 0x52, 0x7c, 0x40, 0xa7, 0xea, 0x88, 0xa3, 0x01, 0x29, 0x3d,
	0x09, 0x43, 0x23, 0xe5, 0x69, 0x8e, 0xc8, 0xe5, 0x7d, 0xa8, 0x4b, 0xd4, 0xb9, 0x36, 0x7a, 0xa4,
	0x38, 0x9b, 0x44, 0x99, 0x28, 0xd4, 0x27, 0xc5, 0xf9, 0x33, 0x06, 0xa4, 0x3c, 0x3d, 0xcf, 0x0b,
	0x1d, 0x47, 0x1a, 0x29, 0xcf, 0x88, 0x81, 0xc8, 0x56, 0x6f, 0xad, 0x46, 0xfc, 0xe7, 0x73, 0xf6,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xf0, 0xf6, 0x18, 0x5d, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BrokerServiceClient interface {
	ListSessions(ctx context.Context, in *SessionFilter, opts ...grpc.CallOption) (*ListSessionsOutput, error)
	CloseSession(ctx context.Context, in *CloseSessionInput, opts ...grpc.CallOption) (*CloseSessionOutput, error)
	DistributeMessage(ctx context.Context, in *MessagePublished, opts ...grpc.CallOption) (*MessagePublishedOutput, error)
	Connect(ctx context.Context, in *ConnectInput, opts ...grpc.CallOption) (*ConnectOutput, error)
	Disconnect(ctx context.Context, in *DisconnectInput, opts ...grpc.CallOption) (*DisconnectOutput, error)
	Publish(ctx context.Context, in *PublishInput, opts ...grpc.CallOption) (*PublishOutput, error)
	Subscribe(ctx context.Context, in *SubscribeInput, opts ...grpc.CallOption) (*SubscribeOutput, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeInput, opts ...grpc.CallOption) (*UnsubscribeOutput, error)
}

type brokerServiceClient struct {
	cc *grpc.ClientConn
}

func NewBrokerServiceClient(cc *grpc.ClientConn) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) ListSessions(ctx context.Context, in *SessionFilter, opts ...grpc.CallOption) (*ListSessionsOutput, error) {
	out := new(ListSessionsOutput)
	err := c.cc.Invoke(ctx, "/BrokerService/ListSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) CloseSession(ctx context.Context, in *CloseSessionInput, opts ...grpc.CallOption) (*CloseSessionOutput, error) {
	out := new(CloseSessionOutput)
	err := c.cc.Invoke(ctx, "/BrokerService/CloseSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) DistributeMessage(ctx context.Context, in *MessagePublished, opts ...grpc.CallOption) (*MessagePublishedOutput, error) {
	out := new(MessagePublishedOutput)
	err := c.cc.Invoke(ctx, "/BrokerService/DistributeMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) Connect(ctx context.Context, in *ConnectInput, opts ...grpc.CallOption) (*ConnectOutput, error) {
	out := new(ConnectOutput)
	err := c.cc.Invoke(ctx, "/BrokerService/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) Disconnect(ctx context.Context, in *DisconnectInput, opts ...grpc.CallOption) (*DisconnectOutput, error) {
	out := new(DisconnectOutput)
	err := c.cc.Invoke(ctx, "/BrokerService/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) Publish(ctx context.Context, in *PublishInput, opts ...grpc.CallOption) (*PublishOutput, error) {
	out := new(PublishOutput)
	err := c.cc.Invoke(ctx, "/BrokerService/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) Subscribe(ctx context.Context, in *SubscribeInput, opts ...grpc.CallOption) (*SubscribeOutput, error) {
	out := new(SubscribeOutput)
	err := c.cc.Invoke(ctx, "/BrokerService/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) Unsubscribe(ctx context.Context, in *UnsubscribeInput, opts ...grpc.CallOption) (*UnsubscribeOutput, error) {
	out := new(UnsubscribeOutput)
	err := c.cc.Invoke(ctx, "/BrokerService/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
type BrokerServiceServer interface {
	ListSessions(context.Context, *SessionFilter) (*ListSessionsOutput, error)
	CloseSession(context.Context, *CloseSessionInput) (*CloseSessionOutput, error)
	DistributeMessage(context.Context, *MessagePublished) (*MessagePublishedOutput, error)
	Connect(context.Context, *ConnectInput) (*ConnectOutput, error)
	Disconnect(context.Context, *DisconnectInput) (*DisconnectOutput, error)
	Publish(context.Context, *PublishInput) (*PublishOutput, error)
	Subscribe(context.Context, *SubscribeInput) (*SubscribeOutput, error)
	Unsubscribe(context.Context, *UnsubscribeInput) (*UnsubscribeOutput, error)
}

// UnimplementedBrokerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBrokerServiceServer struct {
}

func (*UnimplementedBrokerServiceServer) ListSessions(ctx context.Context, req *SessionFilter) (*ListSessionsOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (*UnimplementedBrokerServiceServer) CloseSession(ctx context.Context, req *CloseSessionInput) (*CloseSessionOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (*UnimplementedBrokerServiceServer) DistributeMessage(ctx context.Context, req *MessagePublished) (*MessagePublishedOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistributeMessage not implemented")
}
func (*UnimplementedBrokerServiceServer) Connect(ctx context.Context, req *ConnectInput) (*ConnectOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedBrokerServiceServer) Disconnect(ctx context.Context, req *DisconnectInput) (*DisconnectOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (*UnimplementedBrokerServiceServer) Publish(ctx context.Context, req *PublishInput) (*PublishOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedBrokerServiceServer) Subscribe(ctx context.Context, req *SubscribeInput) (*SubscribeOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedBrokerServiceServer) Unsubscribe(ctx context.Context, req *UnsubscribeInput) (*UnsubscribeOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}

func RegisterBrokerServiceServer(s *grpc.Server, srv BrokerServiceServer) {
	s.RegisterService(&_BrokerService_serviceDesc, srv)
}

func _BrokerService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerService/ListSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).ListSessions(ctx, req.(*SessionFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerService/CloseSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).CloseSession(ctx, req.(*CloseSessionInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_DistributeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagePublished)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).DistributeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerService/DistributeMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).DistributeMessage(ctx, req.(*MessagePublished))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerService/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).Connect(ctx, req.(*ConnectInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerService/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).Disconnect(ctx, req.(*DisconnectInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerService/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).Publish(ctx, req.(*PublishInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerService/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).Subscribe(ctx, req.(*SubscribeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BrokerService/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).Unsubscribe(ctx, req.(*UnsubscribeInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _BrokerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSessions",
			Handler:    _BrokerService_ListSessions_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _BrokerService_CloseSession_Handler,
		},
		{
			MethodName: "DistributeMessage",
			Handler:    _BrokerService_DistributeMessage_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _BrokerService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _BrokerService_Disconnect_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _BrokerService_Publish_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _BrokerService_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _BrokerService_Unsubscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
