// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package subscriptions is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Subscription
*/
package subscriptions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Subscription struct {
	ID        string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	SessionID string `protobuf:"bytes,2,opt,name=SessionID" json:"SessionID,omitempty"`
	Tenant    string `protobuf:"bytes,3,opt,name=Tenant" json:"Tenant,omitempty"`
	Pattern   []byte `protobuf:"bytes,4,opt,name=Pattern,proto3" json:"Pattern,omitempty"`
	Qos       int32  `protobuf:"varint,5,opt,name=Qos" json:"Qos,omitempty"`
	Peer      uint64 `protobuf:"varint,6,opt,name=Peer" json:"Peer,omitempty"`
}

func (m *Subscription) Reset()                    { *m = Subscription{} }
func (m *Subscription) String() string            { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()               {}
func (*Subscription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Subscription) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Subscription) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *Subscription) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Subscription) GetPattern() []byte {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *Subscription) GetQos() int32 {
	if m != nil {
		return m.Qos
	}
	return 0
}

func (m *Subscription) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func init() {
	proto.RegisterType((*Subscription)(nil), "subscriptions.Subscription")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x3b, 0x0e, 0xc2, 0x30,
	0x10, 0x05, 0xe5, 0xfc, 0x50, 0x96, 0x80, 0xd0, 0x16, 0x68, 0x0b, 0x0a, 0x8b, 0xca, 0x15, 0x0d,
	0x57, 0x48, 0x93, 0x2e, 0x38, 0x5c, 0x20, 0x41, 0x2e, 0xd2, 0xd8, 0x91, 0x77, 0x29, 0xb8, 0x07,
	0x07, 0x46, 0x58, 0x20, 0xe8, 0x66, 0xe6, 0x35, 0x0f, 0xd6, 0xf2, 0x58, 0x1c, 0x9f, 0x96, 0x18,
	0x24, 0xe0, 0x86, 0xef, 0x13, 0xdf, 0xe2, 0xbc, 0xc8, 0x1c, 0x3c, 0x1f, 0x9f, 0x0a, 0x9a, 0xe1,
	0xaf, 0xe0, 0x16, 0xb2, 0xae, 0x25, 0xa5, 0x95, 0xa9, 0x6d, 0xd6, 0xb5, 0x78, 0x80, 0x7a, 0x70,
	0xcc, 0x73, 0xf0, 0x5d, 0x4b, 0x59, 0xca, 0xbf, 0x80, 0x7b, 0xa8, 0xae, 0xce, 0x8f, 0x5e, 0x28,
	0x4f, 0xd3, 0xc7, 0x90, 0x60, 0xd5, 0x8f, 0x22, 0x2e, 0x7a, 0x2a, 0xb4, 0x32, 0x8d, 0xfd, 0x2a,
	0xee, 0x20, 0xbf, 0x04, 0xa6, 0x52, 0x2b, 0x53, 0xda, 0x37, 0x22, 0x42, 0xd1, 0x3b, 0x17, 0xa9,
	0xd2, 0xca, 0x14, 0x36, 0xf1, 0x54, 0xa5, 0xb3, 0xe7, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa3,
	0x28, 0xc4, 0xc7, 0xbb, 0x00, 0x00, 0x00,
}
