// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Part struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Part) Reset()         { *m = Part{} }
func (m *Part) String() string { return proto.CompactTextString(m) }
func (*Part) ProtoMessage()    {}
func (*Part) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *Part) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Part.Unmarshal(m, b)
}
func (m *Part) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Part.Marshal(b, m, deterministic)
}
func (m *Part) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Part.Merge(m, src)
}
func (m *Part) XXX_Size() int {
	return xxx_messageInfo_Part.Size(m)
}
func (m *Part) XXX_DiscardUnknown() {
	xxx_messageInfo_Part.DiscardUnknown(m)
}

var xxx_messageInfo_Part proto.InternalMessageInfo

func (m *Part) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Part) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type FullState struct {
	Parts                []*Part  `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FullState) Reset()         { *m = FullState{} }
func (m *FullState) String() string { return proto.CompactTextString(m) }
func (*FullState) ProtoMessage()    {}
func (*FullState) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *FullState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FullState.Unmarshal(m, b)
}
func (m *FullState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FullState.Marshal(b, m, deterministic)
}
func (m *FullState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FullState.Merge(m, src)
}
func (m *FullState) XXX_Size() int {
	return xxx_messageInfo_FullState.Size(m)
}
func (m *FullState) XXX_DiscardUnknown() {
	xxx_messageInfo_FullState.DiscardUnknown(m)
}

var xxx_messageInfo_FullState proto.InternalMessageInfo

func (m *FullState) GetParts() []*Part {
	if m != nil {
		return m.Parts
	}
	return nil
}

type NodeService struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	NetworkAddress       string   `protobuf:"bytes,2,opt,name=NetworkAddress,proto3" json:"NetworkAddress,omitempty"`
	Peer                 string   `protobuf:"bytes,3,opt,name=Peer,proto3" json:"Peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeService) Reset()         { *m = NodeService{} }
func (m *NodeService) String() string { return proto.CompactTextString(m) }
func (*NodeService) ProtoMessage()    {}
func (*NodeService) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *NodeService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeService.Unmarshal(m, b)
}
func (m *NodeService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeService.Marshal(b, m, deterministic)
}
func (m *NodeService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeService.Merge(m, src)
}
func (m *NodeService) XXX_Size() int {
	return xxx_messageInfo_NodeService.Size(m)
}
func (m *NodeService) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeService.DiscardUnknown(m)
}

var xxx_messageInfo_NodeService proto.InternalMessageInfo

func (m *NodeService) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NodeService) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

func (m *NodeService) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

type NodeMeta struct {
	ID                   string         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Services             []*NodeService `protobuf:"bytes,3,rep,name=Services,proto3" json:"Services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NodeMeta) Reset()         { *m = NodeMeta{} }
func (m *NodeMeta) String() string { return proto.CompactTextString(m) }
func (*NodeMeta) ProtoMessage()    {}
func (*NodeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *NodeMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMeta.Unmarshal(m, b)
}
func (m *NodeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMeta.Marshal(b, m, deterministic)
}
func (m *NodeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMeta.Merge(m, src)
}
func (m *NodeMeta) XXX_Size() int {
	return xxx_messageInfo_NodeMeta.Size(m)
}
func (m *NodeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMeta proto.InternalMessageInfo

func (m *NodeMeta) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NodeMeta) GetServices() []*NodeService {
	if m != nil {
		return m.Services
	}
	return nil
}

type Metadata struct {
	ID                   string         `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Hostname             string         `protobuf:"bytes,3,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	LastAdded            int64          `protobuf:"varint,5,opt,name=LastAdded,proto3" json:"LastAdded,omitempty"`
	LastDeleted          int64          `protobuf:"varint,6,opt,name=LastDeleted,proto3" json:"LastDeleted,omitempty"`
	MemoryUsage          *MemoryUsage   `protobuf:"bytes,7,opt,name=MemoryUsage,proto3" json:"MemoryUsage,omitempty"`
	ComputeUsage         *ComputeUsage  `protobuf:"bytes,8,opt,name=ComputeUsage,proto3" json:"ComputeUsage,omitempty"`
	Runtime              string         `protobuf:"bytes,9,opt,name=Runtime,proto3" json:"Runtime,omitempty"`
	HostedServices       []*NodeService `protobuf:"bytes,10,rep,name=HostedServices,proto3" json:"HostedServices,omitempty"`
	Services             []string       `protobuf:"bytes,11,rep,name=Services,proto3" json:"Services,omitempty"`
	Started              int64          `protobuf:"varint,12,opt,name=Started,proto3" json:"Started,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{4}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Metadata) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Metadata) GetLastAdded() int64 {
	if m != nil {
		return m.LastAdded
	}
	return 0
}

func (m *Metadata) GetLastDeleted() int64 {
	if m != nil {
		return m.LastDeleted
	}
	return 0
}

func (m *Metadata) GetMemoryUsage() *MemoryUsage {
	if m != nil {
		return m.MemoryUsage
	}
	return nil
}

func (m *Metadata) GetComputeUsage() *ComputeUsage {
	if m != nil {
		return m.ComputeUsage
	}
	return nil
}

func (m *Metadata) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *Metadata) GetHostedServices() []*NodeService {
	if m != nil {
		return m.HostedServices
	}
	return nil
}

func (m *Metadata) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Metadata) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

type ComputeUsage struct {
	Cores                int64    `protobuf:"varint,1,opt,name=Cores,proto3" json:"Cores,omitempty"`
	Goroutines           int64    `protobuf:"varint,2,opt,name=Goroutines,proto3" json:"Goroutines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeUsage) Reset()         { *m = ComputeUsage{} }
func (m *ComputeUsage) String() string { return proto.CompactTextString(m) }
func (*ComputeUsage) ProtoMessage()    {}
func (*ComputeUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{5}
}

func (m *ComputeUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeUsage.Unmarshal(m, b)
}
func (m *ComputeUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeUsage.Marshal(b, m, deterministic)
}
func (m *ComputeUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeUsage.Merge(m, src)
}
func (m *ComputeUsage) XXX_Size() int {
	return xxx_messageInfo_ComputeUsage.Size(m)
}
func (m *ComputeUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeUsage.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeUsage proto.InternalMessageInfo

func (m *ComputeUsage) GetCores() int64 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *ComputeUsage) GetGoroutines() int64 {
	if m != nil {
		return m.Goroutines
	}
	return 0
}

type MemoryUsage struct {
	Alloc                uint64   `protobuf:"varint,1,opt,name=Alloc,proto3" json:"Alloc,omitempty"`
	TotalAlloc           uint64   `protobuf:"varint,2,opt,name=TotalAlloc,proto3" json:"TotalAlloc,omitempty"`
	Sys                  uint64   `protobuf:"varint,3,opt,name=Sys,proto3" json:"Sys,omitempty"`
	NumGC                uint32   `protobuf:"varint,4,opt,name=NumGC,proto3" json:"NumGC,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemoryUsage) Reset()         { *m = MemoryUsage{} }
func (m *MemoryUsage) String() string { return proto.CompactTextString(m) }
func (*MemoryUsage) ProtoMessage()    {}
func (*MemoryUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{6}
}

func (m *MemoryUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemoryUsage.Unmarshal(m, b)
}
func (m *MemoryUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemoryUsage.Marshal(b, m, deterministic)
}
func (m *MemoryUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemoryUsage.Merge(m, src)
}
func (m *MemoryUsage) XXX_Size() int {
	return xxx_messageInfo_MemoryUsage.Size(m)
}
func (m *MemoryUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_MemoryUsage.DiscardUnknown(m)
}

var xxx_messageInfo_MemoryUsage proto.InternalMessageInfo

func (m *MemoryUsage) GetAlloc() uint64 {
	if m != nil {
		return m.Alloc
	}
	return 0
}

func (m *MemoryUsage) GetTotalAlloc() uint64 {
	if m != nil {
		return m.TotalAlloc
	}
	return 0
}

func (m *MemoryUsage) GetSys() uint64 {
	if m != nil {
		return m.Sys
	}
	return 0
}

func (m *MemoryUsage) GetNumGC() uint32 {
	if m != nil {
		return m.NumGC
	}
	return 0
}

type PeerMetadataList struct {
	Metadatas            []*Metadata `protobuf:"bytes,1,rep,name=Metadatas,proto3" json:"Metadatas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PeerMetadataList) Reset()         { *m = PeerMetadataList{} }
func (m *PeerMetadataList) String() string { return proto.CompactTextString(m) }
func (*PeerMetadataList) ProtoMessage()    {}
func (*PeerMetadataList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{7}
}

func (m *PeerMetadataList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerMetadataList.Unmarshal(m, b)
}
func (m *PeerMetadataList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerMetadataList.Marshal(b, m, deterministic)
}
func (m *PeerMetadataList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerMetadataList.Merge(m, src)
}
func (m *PeerMetadataList) XXX_Size() int {
	return xxx_messageInfo_PeerMetadataList.Size(m)
}
func (m *PeerMetadataList) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerMetadataList.DiscardUnknown(m)
}

var xxx_messageInfo_PeerMetadataList proto.InternalMessageInfo

func (m *PeerMetadataList) GetMetadatas() []*Metadata {
	if m != nil {
		return m.Metadatas
	}
	return nil
}

type StatusInput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusInput) Reset()         { *m = StatusInput{} }
func (m *StatusInput) String() string { return proto.CompactTextString(m) }
func (*StatusInput) ProtoMessage()    {}
func (*StatusInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{8}
}

func (m *StatusInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusInput.Unmarshal(m, b)
}
func (m *StatusInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusInput.Marshal(b, m, deterministic)
}
func (m *StatusInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusInput.Merge(m, src)
}
func (m *StatusInput) XXX_Size() int {
	return xxx_messageInfo_StatusInput.Size(m)
}
func (m *StatusInput) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusInput.DiscardUnknown(m)
}

var xxx_messageInfo_StatusInput proto.InternalMessageInfo

type StatusOutput struct {
	Layer                string   `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusOutput) Reset()         { *m = StatusOutput{} }
func (m *StatusOutput) String() string { return proto.CompactTextString(m) }
func (*StatusOutput) ProtoMessage()    {}
func (*StatusOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{9}
}

func (m *StatusOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusOutput.Unmarshal(m, b)
}
func (m *StatusOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusOutput.Marshal(b, m, deterministic)
}
func (m *StatusOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusOutput.Merge(m, src)
}
func (m *StatusOutput) XXX_Size() int {
	return xxx_messageInfo_StatusOutput.Size(m)
}
func (m *StatusOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StatusOutput proto.InternalMessageInfo

func (m *StatusOutput) GetLayer() string {
	if m != nil {
		return m.Layer
	}
	return ""
}

func (m *StatusOutput) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type SendEventInput struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEventInput) Reset()         { *m = SendEventInput{} }
func (m *SendEventInput) String() string { return proto.CompactTextString(m) }
func (*SendEventInput) ProtoMessage()    {}
func (*SendEventInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{10}
}

func (m *SendEventInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEventInput.Unmarshal(m, b)
}
func (m *SendEventInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEventInput.Marshal(b, m, deterministic)
}
func (m *SendEventInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEventInput.Merge(m, src)
}
func (m *SendEventInput) XXX_Size() int {
	return xxx_messageInfo_SendEventInput.Size(m)
}
func (m *SendEventInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEventInput.DiscardUnknown(m)
}

var xxx_messageInfo_SendEventInput proto.InternalMessageInfo

func (m *SendEventInput) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type SendEventOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEventOutput) Reset()         { *m = SendEventOutput{} }
func (m *SendEventOutput) String() string { return proto.CompactTextString(m) }
func (*SendEventOutput) ProtoMessage()    {}
func (*SendEventOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{11}
}

func (m *SendEventOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEventOutput.Unmarshal(m, b)
}
func (m *SendEventOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEventOutput.Marshal(b, m, deterministic)
}
func (m *SendEventOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEventOutput.Merge(m, src)
}
func (m *SendEventOutput) XXX_Size() int {
	return xxx_messageInfo_SendEventOutput.Size(m)
}
func (m *SendEventOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEventOutput.DiscardUnknown(m)
}

var xxx_messageInfo_SendEventOutput proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Part)(nil), "pb.Part")
	proto.RegisterType((*FullState)(nil), "pb.FullState")
	proto.RegisterType((*NodeService)(nil), "pb.NodeService")
	proto.RegisterType((*NodeMeta)(nil), "pb.NodeMeta")
	proto.RegisterType((*Metadata)(nil), "pb.Metadata")
	proto.RegisterType((*ComputeUsage)(nil), "pb.ComputeUsage")
	proto.RegisterType((*MemoryUsage)(nil), "pb.MemoryUsage")
	proto.RegisterType((*PeerMetadataList)(nil), "pb.PeerMetadataList")
	proto.RegisterType((*StatusInput)(nil), "pb.StatusInput")
	proto.RegisterType((*StatusOutput)(nil), "pb.StatusOutput")
	proto.RegisterType((*SendEventInput)(nil), "pb.SendEventInput")
	proto.RegisterType((*SendEventOutput)(nil), "pb.SendEventOutput")
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x56, 0x9a, 0xb6, 0x4b, 0xae, 0x59, 0x57, 0x0c, 0x42, 0xd6, 0x84, 0xa6, 0xc8, 0x0f, 0xa8,
	0xda, 0xd0, 0x24, 0xc6, 0x24, 0x5e, 0x10, 0xd2, 0xb4, 0xc2, 0x98, 0xd8, 0xc6, 0xe4, 0xc2, 0x03,
	0x8f, 0xee, 0x72, 0x42, 0x65, 0x69, 0x1c, 0xd9, 0xce, 0x50, 0xff, 0x31, 0x3f, 0x03, 0xd9, 0x4e,
	0xd2, 0x74, 0xec, 0xcd, 0xdf, 0x77, 0x77, 0xdf, 0x7d, 0x3e, 0x5f, 0x02, 0x51, 0xb9, 0x38, 0x2e,
	0x95, 0x34, 0x92, 0xf4, 0xca, 0x05, 0x7b, 0x03, 0xfd, 0x5b, 0xa1, 0x0c, 0x99, 0x40, 0xf8, 0x15,
	0xd7, 0x34, 0x48, 0x83, 0x69, 0xcc, 0xed, 0x91, 0x10, 0xe8, 0xcf, 0x84, 0x11, 0xb4, 0x97, 0x06,
	0xd3, 0x84, 0xbb, 0x33, 0x3b, 0x82, 0xf8, 0x73, 0x95, 0xe7, 0x73, 0x23, 0x0c, 0x92, 0x03, 0x18,
	0x94, 0x42, 0x19, 0x4d, 0x83, 0x34, 0x9c, 0x8e, 0x4e, 0xa2, 0xe3, 0x72, 0x71, 0x6c, 0xb5, 0xb8,
	0xa7, 0xd9, 0x4f, 0x18, 0xdd, 0xc8, 0x0c, 0xe7, 0xa8, 0x1e, 0x96, 0x77, 0x48, 0xc6, 0xd0, 0xbb,
	0x9c, 0xd5, 0x0d, 0x7a, 0x97, 0x33, 0xf2, 0x1a, 0xc6, 0x37, 0x68, 0xfe, 0x48, 0x75, 0x7f, 0x96,
	0x65, 0x0a, 0xb5, 0x76, 0x9d, 0x62, 0xfe, 0x88, 0xb5, 0x3e, 0x6e, 0x11, 0x15, 0x0d, 0x5d, 0xd4,
	0x9d, 0xd9, 0x05, 0x44, 0x56, 0xfa, 0x1a, 0x8d, 0xf8, 0x4f, 0xf7, 0x08, 0xa2, 0xba, 0xa5, 0xa6,
	0xa1, 0x73, 0xb6, 0x67, 0x9d, 0x75, 0xac, 0xf0, 0x36, 0x81, 0xfd, 0xed, 0x41, 0x64, 0x55, 0x32,
	0xf1, 0x84, 0xd2, 0x3e, 0x44, 0x5f, 0xa4, 0x36, 0x85, 0x58, 0x61, 0xdd, 0xbd, 0xc5, 0xe4, 0x15,
	0xc4, 0x57, 0x42, 0x9b, 0xb3, 0x2c, 0xc3, 0x8c, 0x0e, 0xd2, 0x60, 0x1a, 0xf2, 0x0d, 0x41, 0x52,
	0x18, 0x59, 0x30, 0xc3, 0x1c, 0x0d, 0x66, 0x74, 0xe8, 0xe2, 0x5d, 0x8a, 0xbc, 0x85, 0xd1, 0x35,
	0xae, 0xa4, 0x5a, 0xff, 0xd0, 0xe2, 0x17, 0xd2, 0x9d, 0x34, 0x68, 0x8c, 0x76, 0x68, 0xde, 0xcd,
	0x21, 0xa7, 0x90, 0x9c, 0xcb, 0x55, 0x59, 0x19, 0xf4, 0x35, 0x91, 0xab, 0x99, 0xd8, 0x9a, 0x2e,
	0xcf, 0xb7, 0xb2, 0x08, 0x85, 0x1d, 0x5e, 0x15, 0x66, 0xb9, 0x42, 0x1a, 0xbb, 0x3b, 0x34, 0x90,
	0xbc, 0x87, 0xb1, 0xbd, 0x0e, 0x66, 0xed, 0xb8, 0xe0, 0xe9, 0x71, 0x3d, 0x4a, 0xb3, 0x73, 0x69,
	0x4b, 0x46, 0x69, 0x68, 0xe7, 0xd2, 0xc6, 0x28, 0xec, 0xcc, 0x8d, 0x50, 0xf6, 0xd6, 0x89, 0xbb,
	0x75, 0x03, 0xd9, 0x6c, 0xdb, 0x3e, 0x79, 0x01, 0x83, 0x73, 0xa9, 0x50, 0xbb, 0x81, 0x87, 0xdc,
	0x03, 0x72, 0x00, 0x70, 0x21, 0x95, 0xac, 0xcc, 0xb2, 0x40, 0xbf, 0x11, 0x21, 0xef, 0x30, 0xec,
	0x7e, 0x6b, 0x6e, 0x56, 0xe4, 0x2c, 0xcf, 0xe5, 0x9d, 0x13, 0xe9, 0x73, 0x0f, 0xac, 0xc8, 0x77,
	0x69, 0x44, 0xee, 0x43, 0x3d, 0x17, 0xea, 0x30, 0x76, 0xd9, 0xe7, 0x6b, 0xed, 0xde, 0xb4, 0xcf,
	0xed, 0xd1, 0xea, 0xdc, 0x54, 0xab, 0x8b, 0x73, 0xda, 0x4f, 0x83, 0xe9, 0x2e, 0xf7, 0x80, 0x7d,
	0x84, 0x89, 0x5d, 0xb7, 0x66, 0x41, 0xae, 0x96, 0xda, 0x90, 0x43, 0x88, 0x1b, 0xdc, 0x6c, 0x7e,
	0xe2, 0x9f, 0xcd, 0x93, 0x7c, 0x13, 0x66, 0xbb, 0x30, 0xb2, 0x9f, 0x4a, 0xa5, 0x2f, 0x8b, 0xb2,
	0x32, 0xec, 0x03, 0x24, 0x1e, 0x7e, 0xab, 0x4c, 0x59, 0x19, 0xdb, 0x34, 0x17, 0x6b, 0x54, 0xf5,
	0xca, 0x79, 0x40, 0x5e, 0xc2, 0x50, 0xbb, 0xac, 0xfa, 0x7b, 0xa8, 0x11, 0x3b, 0x84, 0xf1, 0x1c,
	0x8b, 0xec, 0xd3, 0x03, 0x16, 0xc6, 0xe9, 0xd9, 0x59, 0x97, 0x62, 0x9d, 0x4b, 0x91, 0x39, 0x85,
	0x84, 0x37, 0x90, 0x3d, 0x83, 0xbd, 0x36, 0xd7, 0x37, 0x3b, 0xf9, 0x0d, 0x83, 0x2b, 0xa7, 0x7f,
	0x04, 0x43, 0xef, 0x82, 0xb8, 0x87, 0xee, 0x18, 0xdc, 0x9f, 0x6c, 0x88, 0xda, 0xe2, 0x29, 0xc4,
	0xad, 0x10, 0x21, 0x2e, 0xbc, 0xe5, 0x61, 0xff, 0xf9, 0x16, 0xe7, 0xab, 0x16, 0x43, 0xf7, 0x7f,
	0x79, 0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xa4, 0x67, 0xe8, 0x6b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LayerClient is the client API for Layer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LayerClient interface {
	Status(ctx context.Context, in *StatusInput, opts ...grpc.CallOption) (*StatusOutput, error)
	SendEvent(ctx context.Context, in *SendEventInput, opts ...grpc.CallOption) (*SendEventOutput, error)
}

type layerClient struct {
	cc *grpc.ClientConn
}

func NewLayerClient(cc *grpc.ClientConn) LayerClient {
	return &layerClient{cc}
}

func (c *layerClient) Status(ctx context.Context, in *StatusInput, opts ...grpc.CallOption) (*StatusOutput, error) {
	out := new(StatusOutput)
	err := c.cc.Invoke(ctx, "/pb.Layer/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layerClient) SendEvent(ctx context.Context, in *SendEventInput, opts ...grpc.CallOption) (*SendEventOutput, error) {
	out := new(SendEventOutput)
	err := c.cc.Invoke(ctx, "/pb.Layer/SendEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayerServer is the server API for Layer service.
type LayerServer interface {
	Status(context.Context, *StatusInput) (*StatusOutput, error)
	SendEvent(context.Context, *SendEventInput) (*SendEventOutput, error)
}

// UnimplementedLayerServer can be embedded to have forward compatible implementations.
type UnimplementedLayerServer struct {
}

func (*UnimplementedLayerServer) Status(ctx context.Context, req *StatusInput) (*StatusOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedLayerServer) SendEvent(ctx context.Context, req *SendEventInput) (*SendEventOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEvent not implemented")
}

func RegisterLayerServer(s *grpc.Server, srv LayerServer) {
	s.RegisterService(&_Layer_serviceDesc, srv)
}

func _Layer_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Layer/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerServer).Status(ctx, req.(*StatusInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Layer_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEventInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayerServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Layer/SendEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayerServer).SendEvent(ctx, req.(*SendEventInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Layer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Layer",
	HandlerType: (*LayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Layer_Status_Handler,
		},
		{
			MethodName: "SendEvent",
			Handler:    _Layer_SendEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}
