// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	packet "github.com/vx-labs/mqtt-protocol/packet"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueueCreateInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueCreateInput) Reset()         { *m = QueueCreateInput{} }
func (m *QueueCreateInput) String() string { return proto.CompactTextString(m) }
func (*QueueCreateInput) ProtoMessage()    {}
func (*QueueCreateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *QueueCreateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueCreateInput.Unmarshal(m, b)
}
func (m *QueueCreateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueCreateInput.Marshal(b, m, deterministic)
}
func (m *QueueCreateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueCreateInput.Merge(m, src)
}
func (m *QueueCreateInput) XXX_Size() int {
	return xxx_messageInfo_QueueCreateInput.Size(m)
}
func (m *QueueCreateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueCreateInput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueCreateInput proto.InternalMessageInfo

func (m *QueueCreateInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueueCreateOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueCreateOutput) Reset()         { *m = QueueCreateOutput{} }
func (m *QueueCreateOutput) String() string { return proto.CompactTextString(m) }
func (*QueueCreateOutput) ProtoMessage()    {}
func (*QueueCreateOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *QueueCreateOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueCreateOutput.Unmarshal(m, b)
}
func (m *QueueCreateOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueCreateOutput.Marshal(b, m, deterministic)
}
func (m *QueueCreateOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueCreateOutput.Merge(m, src)
}
func (m *QueueCreateOutput) XXX_Size() int {
	return xxx_messageInfo_QueueCreateOutput.Size(m)
}
func (m *QueueCreateOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueCreateOutput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueCreateOutput proto.InternalMessageInfo

type QueueDeleteInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueDeleteInput) Reset()         { *m = QueueDeleteInput{} }
func (m *QueueDeleteInput) String() string { return proto.CompactTextString(m) }
func (*QueueDeleteInput) ProtoMessage()    {}
func (*QueueDeleteInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *QueueDeleteInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueDeleteInput.Unmarshal(m, b)
}
func (m *QueueDeleteInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueDeleteInput.Marshal(b, m, deterministic)
}
func (m *QueueDeleteInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueDeleteInput.Merge(m, src)
}
func (m *QueueDeleteInput) XXX_Size() int {
	return xxx_messageInfo_QueueDeleteInput.Size(m)
}
func (m *QueueDeleteInput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueDeleteInput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueDeleteInput proto.InternalMessageInfo

func (m *QueueDeleteInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueueDeleteOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueDeleteOutput) Reset()         { *m = QueueDeleteOutput{} }
func (m *QueueDeleteOutput) String() string { return proto.CompactTextString(m) }
func (*QueueDeleteOutput) ProtoMessage()    {}
func (*QueueDeleteOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *QueueDeleteOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueDeleteOutput.Unmarshal(m, b)
}
func (m *QueueDeleteOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueDeleteOutput.Marshal(b, m, deterministic)
}
func (m *QueueDeleteOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueDeleteOutput.Merge(m, src)
}
func (m *QueueDeleteOutput) XXX_Size() int {
	return xxx_messageInfo_QueueDeleteOutput.Size(m)
}
func (m *QueueDeleteOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueDeleteOutput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueDeleteOutput proto.InternalMessageInfo

type QueuePutMessageInput struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Publish              *packet.Publish `protobuf:"bytes,2,opt,name=publish,proto3" json:"publish,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueuePutMessageInput) Reset()         { *m = QueuePutMessageInput{} }
func (m *QueuePutMessageInput) String() string { return proto.CompactTextString(m) }
func (*QueuePutMessageInput) ProtoMessage()    {}
func (*QueuePutMessageInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *QueuePutMessageInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuePutMessageInput.Unmarshal(m, b)
}
func (m *QueuePutMessageInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuePutMessageInput.Marshal(b, m, deterministic)
}
func (m *QueuePutMessageInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuePutMessageInput.Merge(m, src)
}
func (m *QueuePutMessageInput) XXX_Size() int {
	return xxx_messageInfo_QueuePutMessageInput.Size(m)
}
func (m *QueuePutMessageInput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuePutMessageInput.DiscardUnknown(m)
}

var xxx_messageInfo_QueuePutMessageInput proto.InternalMessageInfo

func (m *QueuePutMessageInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueuePutMessageInput) GetPublish() *packet.Publish {
	if m != nil {
		return m.Publish
	}
	return nil
}

type QueuePutMessageOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueuePutMessageOutput) Reset()         { *m = QueuePutMessageOutput{} }
func (m *QueuePutMessageOutput) String() string { return proto.CompactTextString(m) }
func (*QueuePutMessageOutput) ProtoMessage()    {}
func (*QueuePutMessageOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *QueuePutMessageOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuePutMessageOutput.Unmarshal(m, b)
}
func (m *QueuePutMessageOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuePutMessageOutput.Marshal(b, m, deterministic)
}
func (m *QueuePutMessageOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuePutMessageOutput.Merge(m, src)
}
func (m *QueuePutMessageOutput) XXX_Size() int {
	return xxx_messageInfo_QueuePutMessageOutput.Size(m)
}
func (m *QueuePutMessageOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuePutMessageOutput.DiscardUnknown(m)
}

var xxx_messageInfo_QueuePutMessageOutput proto.InternalMessageInfo

type QueueGetMessagesInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueGetMessagesInput) Reset()         { *m = QueueGetMessagesInput{} }
func (m *QueueGetMessagesInput) String() string { return proto.CompactTextString(m) }
func (*QueueGetMessagesInput) ProtoMessage()    {}
func (*QueueGetMessagesInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *QueueGetMessagesInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueGetMessagesInput.Unmarshal(m, b)
}
func (m *QueueGetMessagesInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueGetMessagesInput.Marshal(b, m, deterministic)
}
func (m *QueueGetMessagesInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueGetMessagesInput.Merge(m, src)
}
func (m *QueueGetMessagesInput) XXX_Size() int {
	return xxx_messageInfo_QueueGetMessagesInput.Size(m)
}
func (m *QueueGetMessagesInput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueGetMessagesInput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueGetMessagesInput proto.InternalMessageInfo

func (m *QueueGetMessagesInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueueGetMessagesInput) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type QueueGetMessagesOutput struct {
	Offset               uint64            `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Publishes            []*packet.Publish `protobuf:"bytes,2,rep,name=publishes,proto3" json:"publishes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *QueueGetMessagesOutput) Reset()         { *m = QueueGetMessagesOutput{} }
func (m *QueueGetMessagesOutput) String() string { return proto.CompactTextString(m) }
func (*QueueGetMessagesOutput) ProtoMessage()    {}
func (*QueueGetMessagesOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *QueueGetMessagesOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueGetMessagesOutput.Unmarshal(m, b)
}
func (m *QueueGetMessagesOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueGetMessagesOutput.Marshal(b, m, deterministic)
}
func (m *QueueGetMessagesOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueGetMessagesOutput.Merge(m, src)
}
func (m *QueueGetMessagesOutput) XXX_Size() int {
	return xxx_messageInfo_QueueGetMessagesOutput.Size(m)
}
func (m *QueueGetMessagesOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueGetMessagesOutput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueGetMessagesOutput proto.InternalMessageInfo

func (m *QueueGetMessagesOutput) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueueGetMessagesOutput) GetPublishes() []*packet.Publish {
	if m != nil {
		return m.Publishes
	}
	return nil
}

func init() {
	proto.RegisterType((*QueueCreateInput)(nil), "pb.QueueCreateInput")
	proto.RegisterType((*QueueCreateOutput)(nil), "pb.QueueCreateOutput")
	proto.RegisterType((*QueueDeleteInput)(nil), "pb.QueueDeleteInput")
	proto.RegisterType((*QueueDeleteOutput)(nil), "pb.QueueDeleteOutput")
	proto.RegisterType((*QueuePutMessageInput)(nil), "pb.QueuePutMessageInput")
	proto.RegisterType((*QueuePutMessageOutput)(nil), "pb.QueuePutMessageOutput")
	proto.RegisterType((*QueueGetMessagesInput)(nil), "pb.QueueGetMessagesInput")
	proto.RegisterType((*QueueGetMessagesOutput)(nil), "pb.QueueGetMessagesOutput")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0xd3, 0x7e, 0x5f, 0x6a, 0xb8, 0xc4, 0x7f, 0x23, 0x60, 0xed, 0x8a, 0x74, 0x85, 0x0b,
	0x5a, 0x83, 0x61, 0x6d, 0x8c, 0x24, 0xc6, 0x85, 0x11, 0xf0, 0x01, 0x4c, 0xa7, 0x5c, 0xa0, 0xb1,
	0xd8, 0x91, 0xb9, 0x43, 0xf4, 0x05, 0x7c, 0x6e, 0x93, 0xce, 0x40, 0x27, 0x4d, 0x13, 0x97, 0x9d,
	0x73, 0x7e, 0xe7, 0xde, 0x9c, 0x5b, 0x68, 0xd3, 0xb7, 0x40, 0x19, 0x89, 0x6d, 0x41, 0x05, 0x73,
	0x05, 0x0f, 0x6e, 0x56, 0x19, 0xad, 0x15, 0x8f, 0xd2, 0x62, 0x13, 0xef, 0xbe, 0x86, 0x79, 0xc2,
	0x65, 0xbc, 0xf9, 0x24, 0x1a, 0x96, 0x96, 0xb4, 0xc8, 0x63, 0x91, 0xa4, 0xef, 0x48, 0xb1, 0xe0,
	0x9a, 0x0a, 0x43, 0x38, 0x9b, 0x29, 0x54, 0xf8, 0xb0, 0xc5, 0x84, 0xf0, 0xe9, 0x43, 0x28, 0x62,
	0x27, 0xe0, 0x66, 0x0b, 0xdf, 0xe9, 0x3b, 0x83, 0xd6, 0xdc, 0xcd, 0x16, 0xe1, 0x05, 0x9c, 0x5b,
	0x9e, 0x17, 0x45, 0x42, 0xd1, 0x01, 0x9c, 0x60, 0x8e, 0x7f, 0x81, 0xda, 0x63, 0xc0, 0x19, 0x74,
	0xca, 0xc7, 0xa9, 0xa2, 0x67, 0x94, 0x32, 0x59, 0x35, 0xc3, 0xec, 0x1a, 0x8e, 0x84, 0xe2, 0x79,
	0x26, 0xd7, 0xbe, 0xdb, 0x77, 0x06, 0xed, 0xd1, 0x69, 0xa4, 0x97, 0x8f, 0xa6, 0xfa, 0x79, 0xbe,
	0xd7, 0xc3, 0x4b, 0xe8, 0xd6, 0x22, 0xcd, 0xac, 0x3b, 0x23, 0x3c, 0xe2, 0x5e, 0x90, 0xcd, 0xc3,
	0x7a, 0xe0, 0x15, 0xcb, 0xa5, 0x44, 0x2a, 0x67, 0xfd, 0x9f, 0x9b, 0xaf, 0xf0, 0x0d, 0x7a, 0xf5,
	0x00, 0x1d, 0x6d, 0x11, 0x8e, 0x4d, 0xb0, 0x21, 0xb4, 0xcc, 0x5a, 0x28, 0x7d, 0xb7, 0xff, 0xaf,
	0x69, 0xf1, 0xca, 0x31, 0xfa, 0x71, 0xe1, 0xb8, 0x9c, 0x20, 0x5f, 0x71, 0xbb, 0xcb, 0x52, 0x64,
	0x63, 0xf0, 0x74, 0xd1, 0xac, 0x13, 0x09, 0x1e, 0xd5, 0xaf, 0x13, 0x74, 0x6b, 0xaf, 0x66, 0x9f,
	0x31, 0x78, 0xba, 0x66, 0x0b, 0xb3, 0x6e, 0x63, 0x61, 0xf6, 0x35, 0xd8, 0x3d, 0x40, 0xd5, 0x1a,
	0xf3, 0x0f, 0xa6, 0xda, 0x75, 0x82, 0xab, 0x06, 0xc5, 0x44, 0x4c, 0xa0, 0x6d, 0xd5, 0xc3, 0x2a,
	0x67, 0xbd, 0xf5, 0x20, 0x68, 0x92, 0x74, 0x0a, 0xf7, 0xca, 0xff, 0xf1, 0xf6, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x84, 0x23, 0x23, 0xeb, 0xd4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueuesServiceClient is the client API for QueuesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueuesServiceClient interface {
	Create(ctx context.Context, in *QueueCreateInput, opts ...grpc.CallOption) (*QueueCreateOutput, error)
	Delete(ctx context.Context, in *QueueDeleteInput, opts ...grpc.CallOption) (*QueueDeleteOutput, error)
	PutMessage(ctx context.Context, in *QueuePutMessageInput, opts ...grpc.CallOption) (*QueuePutMessageOutput, error)
	GetMessages(ctx context.Context, in *QueueGetMessagesInput, opts ...grpc.CallOption) (*QueueGetMessagesOutput, error)
}

type queuesServiceClient struct {
	cc *grpc.ClientConn
}

func NewQueuesServiceClient(cc *grpc.ClientConn) QueuesServiceClient {
	return &queuesServiceClient{cc}
}

func (c *queuesServiceClient) Create(ctx context.Context, in *QueueCreateInput, opts ...grpc.CallOption) (*QueueCreateOutput, error) {
	out := new(QueueCreateOutput)
	err := c.cc.Invoke(ctx, "/pb.QueuesService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queuesServiceClient) Delete(ctx context.Context, in *QueueDeleteInput, opts ...grpc.CallOption) (*QueueDeleteOutput, error) {
	out := new(QueueDeleteOutput)
	err := c.cc.Invoke(ctx, "/pb.QueuesService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queuesServiceClient) PutMessage(ctx context.Context, in *QueuePutMessageInput, opts ...grpc.CallOption) (*QueuePutMessageOutput, error) {
	out := new(QueuePutMessageOutput)
	err := c.cc.Invoke(ctx, "/pb.QueuesService/PutMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queuesServiceClient) GetMessages(ctx context.Context, in *QueueGetMessagesInput, opts ...grpc.CallOption) (*QueueGetMessagesOutput, error) {
	out := new(QueueGetMessagesOutput)
	err := c.cc.Invoke(ctx, "/pb.QueuesService/GetMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueuesServiceServer is the server API for QueuesService service.
type QueuesServiceServer interface {
	Create(context.Context, *QueueCreateInput) (*QueueCreateOutput, error)
	Delete(context.Context, *QueueDeleteInput) (*QueueDeleteOutput, error)
	PutMessage(context.Context, *QueuePutMessageInput) (*QueuePutMessageOutput, error)
	GetMessages(context.Context, *QueueGetMessagesInput) (*QueueGetMessagesOutput, error)
}

// UnimplementedQueuesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQueuesServiceServer struct {
}

func (*UnimplementedQueuesServiceServer) Create(ctx context.Context, req *QueueCreateInput) (*QueueCreateOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedQueuesServiceServer) Delete(ctx context.Context, req *QueueDeleteInput) (*QueueDeleteOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedQueuesServiceServer) PutMessage(ctx context.Context, req *QueuePutMessageInput) (*QueuePutMessageOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMessage not implemented")
}
func (*UnimplementedQueuesServiceServer) GetMessages(ctx context.Context, req *QueueGetMessagesInput) (*QueueGetMessagesOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessages not implemented")
}

func RegisterQueuesServiceServer(s *grpc.Server, srv QueuesServiceServer) {
	s.RegisterService(&_QueuesService_serviceDesc, srv)
}

func _QueuesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueCreateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QueuesService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesServiceServer).Create(ctx, req.(*QueueCreateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueuesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueDeleteInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QueuesService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesServiceServer).Delete(ctx, req.(*QueueDeleteInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueuesService_PutMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueuePutMessageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesServiceServer).PutMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QueuesService/PutMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesServiceServer).PutMessage(ctx, req.(*QueuePutMessageInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueuesService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueGetMessagesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QueuesService/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesServiceServer).GetMessages(ctx, req.(*QueueGetMessagesInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _QueuesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.QueuesService",
	HandlerType: (*QueuesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _QueuesService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _QueuesService_Delete_Handler,
		},
		{
			MethodName: "PutMessage",
			Handler:    _QueuesService_PutMessage_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _QueuesService_GetMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types.proto",
}
