// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	packet "github.com/vx-labs/mqtt-protocol/packet"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueueMetadata struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Volatile             bool     `protobuf:"varint,2,opt,name=volatile,proto3" json:"volatile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueMetadata) Reset()         { *m = QueueMetadata{} }
func (m *QueueMetadata) String() string { return proto.CompactTextString(m) }
func (*QueueMetadata) ProtoMessage()    {}
func (*QueueMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *QueueMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueMetadata.Unmarshal(m, b)
}
func (m *QueueMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueMetadata.Marshal(b, m, deterministic)
}
func (m *QueueMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueMetadata.Merge(m, src)
}
func (m *QueueMetadata) XXX_Size() int {
	return xxx_messageInfo_QueueMetadata.Size(m)
}
func (m *QueueMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_QueueMetadata proto.InternalMessageInfo

func (m *QueueMetadata) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *QueueMetadata) GetVolatile() bool {
	if m != nil {
		return m.Volatile
	}
	return false
}

type QueueMetadataList struct {
	Queues               []*QueueMetadata `protobuf:"bytes,1,rep,name=Queues,proto3" json:"Queues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *QueueMetadataList) Reset()         { *m = QueueMetadataList{} }
func (m *QueueMetadataList) String() string { return proto.CompactTextString(m) }
func (*QueueMetadataList) ProtoMessage()    {}
func (*QueueMetadataList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *QueueMetadataList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueMetadataList.Unmarshal(m, b)
}
func (m *QueueMetadataList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueMetadataList.Marshal(b, m, deterministic)
}
func (m *QueueMetadataList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueMetadataList.Merge(m, src)
}
func (m *QueueMetadataList) XXX_Size() int {
	return xxx_messageInfo_QueueMetadataList.Size(m)
}
func (m *QueueMetadataList) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueMetadataList.DiscardUnknown(m)
}

var xxx_messageInfo_QueueMetadataList proto.InternalMessageInfo

func (m *QueueMetadataList) GetQueues() []*QueueMetadata {
	if m != nil {
		return m.Queues
	}
	return nil
}

type QueueCreateInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueCreateInput) Reset()         { *m = QueueCreateInput{} }
func (m *QueueCreateInput) String() string { return proto.CompactTextString(m) }
func (*QueueCreateInput) ProtoMessage()    {}
func (*QueueCreateInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *QueueCreateInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueCreateInput.Unmarshal(m, b)
}
func (m *QueueCreateInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueCreateInput.Marshal(b, m, deterministic)
}
func (m *QueueCreateInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueCreateInput.Merge(m, src)
}
func (m *QueueCreateInput) XXX_Size() int {
	return xxx_messageInfo_QueueCreateInput.Size(m)
}
func (m *QueueCreateInput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueCreateInput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueCreateInput proto.InternalMessageInfo

func (m *QueueCreateInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueueCreateOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueCreateOutput) Reset()         { *m = QueueCreateOutput{} }
func (m *QueueCreateOutput) String() string { return proto.CompactTextString(m) }
func (*QueueCreateOutput) ProtoMessage()    {}
func (*QueueCreateOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *QueueCreateOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueCreateOutput.Unmarshal(m, b)
}
func (m *QueueCreateOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueCreateOutput.Marshal(b, m, deterministic)
}
func (m *QueueCreateOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueCreateOutput.Merge(m, src)
}
func (m *QueueCreateOutput) XXX_Size() int {
	return xxx_messageInfo_QueueCreateOutput.Size(m)
}
func (m *QueueCreateOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueCreateOutput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueCreateOutput proto.InternalMessageInfo

type QueueDeleteInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueDeleteInput) Reset()         { *m = QueueDeleteInput{} }
func (m *QueueDeleteInput) String() string { return proto.CompactTextString(m) }
func (*QueueDeleteInput) ProtoMessage()    {}
func (*QueueDeleteInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *QueueDeleteInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueDeleteInput.Unmarshal(m, b)
}
func (m *QueueDeleteInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueDeleteInput.Marshal(b, m, deterministic)
}
func (m *QueueDeleteInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueDeleteInput.Merge(m, src)
}
func (m *QueueDeleteInput) XXX_Size() int {
	return xxx_messageInfo_QueueDeleteInput.Size(m)
}
func (m *QueueDeleteInput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueDeleteInput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueDeleteInput proto.InternalMessageInfo

func (m *QueueDeleteInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueueDeleteOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueDeleteOutput) Reset()         { *m = QueueDeleteOutput{} }
func (m *QueueDeleteOutput) String() string { return proto.CompactTextString(m) }
func (*QueueDeleteOutput) ProtoMessage()    {}
func (*QueueDeleteOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *QueueDeleteOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueDeleteOutput.Unmarshal(m, b)
}
func (m *QueueDeleteOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueDeleteOutput.Marshal(b, m, deterministic)
}
func (m *QueueDeleteOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueDeleteOutput.Merge(m, src)
}
func (m *QueueDeleteOutput) XXX_Size() int {
	return xxx_messageInfo_QueueDeleteOutput.Size(m)
}
func (m *QueueDeleteOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueDeleteOutput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueDeleteOutput proto.InternalMessageInfo

type QueuePutMessageInput struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Publish              *packet.Publish `protobuf:"bytes,2,opt,name=publish,proto3" json:"publish,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueuePutMessageInput) Reset()         { *m = QueuePutMessageInput{} }
func (m *QueuePutMessageInput) String() string { return proto.CompactTextString(m) }
func (*QueuePutMessageInput) ProtoMessage()    {}
func (*QueuePutMessageInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *QueuePutMessageInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuePutMessageInput.Unmarshal(m, b)
}
func (m *QueuePutMessageInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuePutMessageInput.Marshal(b, m, deterministic)
}
func (m *QueuePutMessageInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuePutMessageInput.Merge(m, src)
}
func (m *QueuePutMessageInput) XXX_Size() int {
	return xxx_messageInfo_QueuePutMessageInput.Size(m)
}
func (m *QueuePutMessageInput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuePutMessageInput.DiscardUnknown(m)
}

var xxx_messageInfo_QueuePutMessageInput proto.InternalMessageInfo

func (m *QueuePutMessageInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueuePutMessageInput) GetPublish() *packet.Publish {
	if m != nil {
		return m.Publish
	}
	return nil
}

type QueuePutMessageOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueuePutMessageOutput) Reset()         { *m = QueuePutMessageOutput{} }
func (m *QueuePutMessageOutput) String() string { return proto.CompactTextString(m) }
func (*QueuePutMessageOutput) ProtoMessage()    {}
func (*QueuePutMessageOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *QueuePutMessageOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuePutMessageOutput.Unmarshal(m, b)
}
func (m *QueuePutMessageOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuePutMessageOutput.Marshal(b, m, deterministic)
}
func (m *QueuePutMessageOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuePutMessageOutput.Merge(m, src)
}
func (m *QueuePutMessageOutput) XXX_Size() int {
	return xxx_messageInfo_QueuePutMessageOutput.Size(m)
}
func (m *QueuePutMessageOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuePutMessageOutput.DiscardUnknown(m)
}

var xxx_messageInfo_QueuePutMessageOutput proto.InternalMessageInfo

type QueuePutMessageBatchInput struct {
	Batches              []*QueuePutMessageInput `protobuf:"bytes,1,rep,name=Batches,proto3" json:"Batches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *QueuePutMessageBatchInput) Reset()         { *m = QueuePutMessageBatchInput{} }
func (m *QueuePutMessageBatchInput) String() string { return proto.CompactTextString(m) }
func (*QueuePutMessageBatchInput) ProtoMessage()    {}
func (*QueuePutMessageBatchInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *QueuePutMessageBatchInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuePutMessageBatchInput.Unmarshal(m, b)
}
func (m *QueuePutMessageBatchInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuePutMessageBatchInput.Marshal(b, m, deterministic)
}
func (m *QueuePutMessageBatchInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuePutMessageBatchInput.Merge(m, src)
}
func (m *QueuePutMessageBatchInput) XXX_Size() int {
	return xxx_messageInfo_QueuePutMessageBatchInput.Size(m)
}
func (m *QueuePutMessageBatchInput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuePutMessageBatchInput.DiscardUnknown(m)
}

var xxx_messageInfo_QueuePutMessageBatchInput proto.InternalMessageInfo

func (m *QueuePutMessageBatchInput) GetBatches() []*QueuePutMessageInput {
	if m != nil {
		return m.Batches
	}
	return nil
}

type QueuePutMessageBatchOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueuePutMessageBatchOutput) Reset()         { *m = QueuePutMessageBatchOutput{} }
func (m *QueuePutMessageBatchOutput) String() string { return proto.CompactTextString(m) }
func (*QueuePutMessageBatchOutput) ProtoMessage()    {}
func (*QueuePutMessageBatchOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *QueuePutMessageBatchOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuePutMessageBatchOutput.Unmarshal(m, b)
}
func (m *QueuePutMessageBatchOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuePutMessageBatchOutput.Marshal(b, m, deterministic)
}
func (m *QueuePutMessageBatchOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuePutMessageBatchOutput.Merge(m, src)
}
func (m *QueuePutMessageBatchOutput) XXX_Size() int {
	return xxx_messageInfo_QueuePutMessageBatchOutput.Size(m)
}
func (m *QueuePutMessageBatchOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuePutMessageBatchOutput.DiscardUnknown(m)
}

var xxx_messageInfo_QueuePutMessageBatchOutput proto.InternalMessageInfo

type QueueGetMessagesInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueGetMessagesInput) Reset()         { *m = QueueGetMessagesInput{} }
func (m *QueueGetMessagesInput) String() string { return proto.CompactTextString(m) }
func (*QueueGetMessagesInput) ProtoMessage()    {}
func (*QueueGetMessagesInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *QueueGetMessagesInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueGetMessagesInput.Unmarshal(m, b)
}
func (m *QueueGetMessagesInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueGetMessagesInput.Marshal(b, m, deterministic)
}
func (m *QueueGetMessagesInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueGetMessagesInput.Merge(m, src)
}
func (m *QueueGetMessagesInput) XXX_Size() int {
	return xxx_messageInfo_QueueGetMessagesInput.Size(m)
}
func (m *QueueGetMessagesInput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueGetMessagesInput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueGetMessagesInput proto.InternalMessageInfo

func (m *QueueGetMessagesInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueueGetMessagesInput) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type AckMessageInput struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMessageInput) Reset()         { *m = AckMessageInput{} }
func (m *AckMessageInput) String() string { return proto.CompactTextString(m) }
func (*AckMessageInput) ProtoMessage()    {}
func (*AckMessageInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *AckMessageInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessageInput.Unmarshal(m, b)
}
func (m *AckMessageInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessageInput.Marshal(b, m, deterministic)
}
func (m *AckMessageInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessageInput.Merge(m, src)
}
func (m *AckMessageInput) XXX_Size() int {
	return xxx_messageInfo_AckMessageInput.Size(m)
}
func (m *AckMessageInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessageInput.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessageInput proto.InternalMessageInfo

func (m *AckMessageInput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AckMessageInput) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type AckMessageOutput struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckMessageOutput) Reset()         { *m = AckMessageOutput{} }
func (m *AckMessageOutput) String() string { return proto.CompactTextString(m) }
func (*AckMessageOutput) ProtoMessage()    {}
func (*AckMessageOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{12}
}

func (m *AckMessageOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckMessageOutput.Unmarshal(m, b)
}
func (m *AckMessageOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckMessageOutput.Marshal(b, m, deterministic)
}
func (m *AckMessageOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckMessageOutput.Merge(m, src)
}
func (m *AckMessageOutput) XXX_Size() int {
	return xxx_messageInfo_AckMessageOutput.Size(m)
}
func (m *AckMessageOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_AckMessageOutput.DiscardUnknown(m)
}

var xxx_messageInfo_AckMessageOutput proto.InternalMessageInfo

type QueueGetMessagesOutput struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Offset               uint64          `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Publish              *packet.Publish `protobuf:"bytes,3,opt,name=publish,proto3" json:"publish,omitempty"`
	AckOffset            uint64          `protobuf:"varint,4,opt,name=ackOffset,proto3" json:"ackOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *QueueGetMessagesOutput) Reset()         { *m = QueueGetMessagesOutput{} }
func (m *QueueGetMessagesOutput) String() string { return proto.CompactTextString(m) }
func (*QueueGetMessagesOutput) ProtoMessage()    {}
func (*QueueGetMessagesOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{13}
}

func (m *QueueGetMessagesOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueGetMessagesOutput.Unmarshal(m, b)
}
func (m *QueueGetMessagesOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueGetMessagesOutput.Marshal(b, m, deterministic)
}
func (m *QueueGetMessagesOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueGetMessagesOutput.Merge(m, src)
}
func (m *QueueGetMessagesOutput) XXX_Size() int {
	return xxx_messageInfo_QueueGetMessagesOutput.Size(m)
}
func (m *QueueGetMessagesOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueGetMessagesOutput.DiscardUnknown(m)
}

var xxx_messageInfo_QueueGetMessagesOutput proto.InternalMessageInfo

func (m *QueueGetMessagesOutput) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueueGetMessagesOutput) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueueGetMessagesOutput) GetPublish() *packet.Publish {
	if m != nil {
		return m.Publish
	}
	return nil
}

func (m *QueueGetMessagesOutput) GetAckOffset() uint64 {
	if m != nil {
		return m.AckOffset
	}
	return 0
}

type StreamMessageOutput struct {
	Offset               uint64                    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Batches              []*QueueGetMessagesOutput `protobuf:"bytes,2,rep,name=batches,proto3" json:"batches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *StreamMessageOutput) Reset()         { *m = StreamMessageOutput{} }
func (m *StreamMessageOutput) String() string { return proto.CompactTextString(m) }
func (*StreamMessageOutput) ProtoMessage()    {}
func (*StreamMessageOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{14}
}

func (m *StreamMessageOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMessageOutput.Unmarshal(m, b)
}
func (m *StreamMessageOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMessageOutput.Marshal(b, m, deterministic)
}
func (m *StreamMessageOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMessageOutput.Merge(m, src)
}
func (m *StreamMessageOutput) XXX_Size() int {
	return xxx_messageInfo_StreamMessageOutput.Size(m)
}
func (m *StreamMessageOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMessageOutput.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMessageOutput proto.InternalMessageInfo

func (m *StreamMessageOutput) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *StreamMessageOutput) GetBatches() []*QueueGetMessagesOutput {
	if m != nil {
		return m.Batches
	}
	return nil
}

type QueuesStateTransitionSet struct {
	Events               []*QueuesStateTransition `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *QueuesStateTransitionSet) Reset()         { *m = QueuesStateTransitionSet{} }
func (m *QueuesStateTransitionSet) String() string { return proto.CompactTextString(m) }
func (*QueuesStateTransitionSet) ProtoMessage()    {}
func (*QueuesStateTransitionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{15}
}

func (m *QueuesStateTransitionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuesStateTransitionSet.Unmarshal(m, b)
}
func (m *QueuesStateTransitionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuesStateTransitionSet.Marshal(b, m, deterministic)
}
func (m *QueuesStateTransitionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuesStateTransitionSet.Merge(m, src)
}
func (m *QueuesStateTransitionSet) XXX_Size() int {
	return xxx_messageInfo_QueuesStateTransitionSet.Size(m)
}
func (m *QueuesStateTransitionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuesStateTransitionSet.DiscardUnknown(m)
}

var xxx_messageInfo_QueuesStateTransitionSet proto.InternalMessageInfo

func (m *QueuesStateTransitionSet) GetEvents() []*QueuesStateTransition {
	if m != nil {
		return m.Events
	}
	return nil
}

type QueuesStateTransition struct {
	Kind                 string                                  `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	QueueCreated         *QueueStateTransitionQueueCreated       `protobuf:"bytes,2,opt,name=QueueCreated,proto3" json:"QueueCreated,omitempty"`
	QueueDeleted         *QueueStateTransitionQueueDeleted       `protobuf:"bytes,3,opt,name=QueueDeleted,proto3" json:"QueueDeleted,omitempty"`
	QueueMessagePut      *QueueStateTransitionMessagePut         `protobuf:"bytes,4,opt,name=QueueMessagePut,proto3" json:"QueueMessagePut,omitempty"`
	QueueMessagePutBatch *QueueStateTransitionMessagePutBatch    `protobuf:"bytes,5,opt,name=QueueMessagePutBatch,proto3" json:"QueueMessagePutBatch,omitempty"`
	MessageInflightSet   *QueueStateTransitionMessageInflightSet `protobuf:"bytes,6,opt,name=MessageInflightSet,proto3" json:"MessageInflightSet,omitempty"`
	MessageDeleted       *QueueStateTransitionMessageDeleted     `protobuf:"bytes,7,opt,name=MessageDeleted,proto3" json:"MessageDeleted,omitempty"`
	MessageAcked         *QueueStateTransitionMessageAcked       `protobuf:"bytes,8,opt,name=MessageAcked,proto3" json:"MessageAcked,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *QueuesStateTransition) Reset()         { *m = QueuesStateTransition{} }
func (m *QueuesStateTransition) String() string { return proto.CompactTextString(m) }
func (*QueuesStateTransition) ProtoMessage()    {}
func (*QueuesStateTransition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{16}
}

func (m *QueuesStateTransition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueuesStateTransition.Unmarshal(m, b)
}
func (m *QueuesStateTransition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueuesStateTransition.Marshal(b, m, deterministic)
}
func (m *QueuesStateTransition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueuesStateTransition.Merge(m, src)
}
func (m *QueuesStateTransition) XXX_Size() int {
	return xxx_messageInfo_QueuesStateTransition.Size(m)
}
func (m *QueuesStateTransition) XXX_DiscardUnknown() {
	xxx_messageInfo_QueuesStateTransition.DiscardUnknown(m)
}

var xxx_messageInfo_QueuesStateTransition proto.InternalMessageInfo

func (m *QueuesStateTransition) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *QueuesStateTransition) GetQueueCreated() *QueueStateTransitionQueueCreated {
	if m != nil {
		return m.QueueCreated
	}
	return nil
}

func (m *QueuesStateTransition) GetQueueDeleted() *QueueStateTransitionQueueDeleted {
	if m != nil {
		return m.QueueDeleted
	}
	return nil
}

func (m *QueuesStateTransition) GetQueueMessagePut() *QueueStateTransitionMessagePut {
	if m != nil {
		return m.QueueMessagePut
	}
	return nil
}

func (m *QueuesStateTransition) GetQueueMessagePutBatch() *QueueStateTransitionMessagePutBatch {
	if m != nil {
		return m.QueueMessagePutBatch
	}
	return nil
}

func (m *QueuesStateTransition) GetMessageInflightSet() *QueueStateTransitionMessageInflightSet {
	if m != nil {
		return m.MessageInflightSet
	}
	return nil
}

func (m *QueuesStateTransition) GetMessageDeleted() *QueueStateTransitionMessageDeleted {
	if m != nil {
		return m.MessageDeleted
	}
	return nil
}

func (m *QueuesStateTransition) GetMessageAcked() *QueueStateTransitionMessageAcked {
	if m != nil {
		return m.MessageAcked
	}
	return nil
}

type QueueStateTransitionQueueCreated struct {
	Input                *QueueMetadata `protobuf:"bytes,1,opt,name=Input,proto3" json:"Input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueueStateTransitionQueueCreated) Reset()         { *m = QueueStateTransitionQueueCreated{} }
func (m *QueueStateTransitionQueueCreated) String() string { return proto.CompactTextString(m) }
func (*QueueStateTransitionQueueCreated) ProtoMessage()    {}
func (*QueueStateTransitionQueueCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{17}
}

func (m *QueueStateTransitionQueueCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueStateTransitionQueueCreated.Unmarshal(m, b)
}
func (m *QueueStateTransitionQueueCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueStateTransitionQueueCreated.Marshal(b, m, deterministic)
}
func (m *QueueStateTransitionQueueCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueStateTransitionQueueCreated.Merge(m, src)
}
func (m *QueueStateTransitionQueueCreated) XXX_Size() int {
	return xxx_messageInfo_QueueStateTransitionQueueCreated.Size(m)
}
func (m *QueueStateTransitionQueueCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueStateTransitionQueueCreated.DiscardUnknown(m)
}

var xxx_messageInfo_QueueStateTransitionQueueCreated proto.InternalMessageInfo

func (m *QueueStateTransitionQueueCreated) GetInput() *QueueMetadata {
	if m != nil {
		return m.Input
	}
	return nil
}

type QueueStateTransitionQueueDeleted struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueStateTransitionQueueDeleted) Reset()         { *m = QueueStateTransitionQueueDeleted{} }
func (m *QueueStateTransitionQueueDeleted) String() string { return proto.CompactTextString(m) }
func (*QueueStateTransitionQueueDeleted) ProtoMessage()    {}
func (*QueueStateTransitionQueueDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{18}
}

func (m *QueueStateTransitionQueueDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueStateTransitionQueueDeleted.Unmarshal(m, b)
}
func (m *QueueStateTransitionQueueDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueStateTransitionQueueDeleted.Marshal(b, m, deterministic)
}
func (m *QueueStateTransitionQueueDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueStateTransitionQueueDeleted.Merge(m, src)
}
func (m *QueueStateTransitionQueueDeleted) XXX_Size() int {
	return xxx_messageInfo_QueueStateTransitionQueueDeleted.Size(m)
}
func (m *QueueStateTransitionQueueDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueStateTransitionQueueDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_QueueStateTransitionQueueDeleted proto.InternalMessageInfo

func (m *QueueStateTransitionQueueDeleted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type QueueStateTransitionMessagePut struct {
	QueueID              string   `protobuf:"bytes,1,opt,name=QueueID,proto3" json:"QueueID,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueStateTransitionMessagePut) Reset()         { *m = QueueStateTransitionMessagePut{} }
func (m *QueueStateTransitionMessagePut) String() string { return proto.CompactTextString(m) }
func (*QueueStateTransitionMessagePut) ProtoMessage()    {}
func (*QueueStateTransitionMessagePut) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{19}
}

func (m *QueueStateTransitionMessagePut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueStateTransitionMessagePut.Unmarshal(m, b)
}
func (m *QueueStateTransitionMessagePut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueStateTransitionMessagePut.Marshal(b, m, deterministic)
}
func (m *QueueStateTransitionMessagePut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueStateTransitionMessagePut.Merge(m, src)
}
func (m *QueueStateTransitionMessagePut) XXX_Size() int {
	return xxx_messageInfo_QueueStateTransitionMessagePut.Size(m)
}
func (m *QueueStateTransitionMessagePut) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueStateTransitionMessagePut.DiscardUnknown(m)
}

var xxx_messageInfo_QueueStateTransitionMessagePut proto.InternalMessageInfo

func (m *QueueStateTransitionMessagePut) GetQueueID() string {
	if m != nil {
		return m.QueueID
	}
	return ""
}

func (m *QueueStateTransitionMessagePut) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueueStateTransitionMessagePut) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type QueueStateTransitionMessageInflightSet struct {
	QueueID              string   `protobuf:"bytes,1,opt,name=QueueID,proto3" json:"QueueID,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Deadline             uint64   `protobuf:"varint,3,opt,name=Deadline,proto3" json:"Deadline,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueStateTransitionMessageInflightSet) Reset() {
	*m = QueueStateTransitionMessageInflightSet{}
}
func (m *QueueStateTransitionMessageInflightSet) String() string { return proto.CompactTextString(m) }
func (*QueueStateTransitionMessageInflightSet) ProtoMessage()    {}
func (*QueueStateTransitionMessageInflightSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{20}
}

func (m *QueueStateTransitionMessageInflightSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueStateTransitionMessageInflightSet.Unmarshal(m, b)
}
func (m *QueueStateTransitionMessageInflightSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueStateTransitionMessageInflightSet.Marshal(b, m, deterministic)
}
func (m *QueueStateTransitionMessageInflightSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueStateTransitionMessageInflightSet.Merge(m, src)
}
func (m *QueueStateTransitionMessageInflightSet) XXX_Size() int {
	return xxx_messageInfo_QueueStateTransitionMessageInflightSet.Size(m)
}
func (m *QueueStateTransitionMessageInflightSet) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueStateTransitionMessageInflightSet.DiscardUnknown(m)
}

var xxx_messageInfo_QueueStateTransitionMessageInflightSet proto.InternalMessageInfo

func (m *QueueStateTransitionMessageInflightSet) GetQueueID() string {
	if m != nil {
		return m.QueueID
	}
	return ""
}

func (m *QueueStateTransitionMessageInflightSet) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueueStateTransitionMessageInflightSet) GetDeadline() uint64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

type QueueStateTransitionMessageAcked struct {
	QueueID              string   `protobuf:"bytes,1,opt,name=QueueID,proto3" json:"QueueID,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueStateTransitionMessageAcked) Reset()         { *m = QueueStateTransitionMessageAcked{} }
func (m *QueueStateTransitionMessageAcked) String() string { return proto.CompactTextString(m) }
func (*QueueStateTransitionMessageAcked) ProtoMessage()    {}
func (*QueueStateTransitionMessageAcked) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{21}
}

func (m *QueueStateTransitionMessageAcked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueStateTransitionMessageAcked.Unmarshal(m, b)
}
func (m *QueueStateTransitionMessageAcked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueStateTransitionMessageAcked.Marshal(b, m, deterministic)
}
func (m *QueueStateTransitionMessageAcked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueStateTransitionMessageAcked.Merge(m, src)
}
func (m *QueueStateTransitionMessageAcked) XXX_Size() int {
	return xxx_messageInfo_QueueStateTransitionMessageAcked.Size(m)
}
func (m *QueueStateTransitionMessageAcked) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueStateTransitionMessageAcked.DiscardUnknown(m)
}

var xxx_messageInfo_QueueStateTransitionMessageAcked proto.InternalMessageInfo

func (m *QueueStateTransitionMessageAcked) GetQueueID() string {
	if m != nil {
		return m.QueueID
	}
	return ""
}

func (m *QueueStateTransitionMessageAcked) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type QueueStateTransitionMessageDeleted struct {
	QueueID              string   `protobuf:"bytes,1,opt,name=QueueID,proto3" json:"QueueID,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueStateTransitionMessageDeleted) Reset()         { *m = QueueStateTransitionMessageDeleted{} }
func (m *QueueStateTransitionMessageDeleted) String() string { return proto.CompactTextString(m) }
func (*QueueStateTransitionMessageDeleted) ProtoMessage()    {}
func (*QueueStateTransitionMessageDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{22}
}

func (m *QueueStateTransitionMessageDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueStateTransitionMessageDeleted.Unmarshal(m, b)
}
func (m *QueueStateTransitionMessageDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueStateTransitionMessageDeleted.Marshal(b, m, deterministic)
}
func (m *QueueStateTransitionMessageDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueStateTransitionMessageDeleted.Merge(m, src)
}
func (m *QueueStateTransitionMessageDeleted) XXX_Size() int {
	return xxx_messageInfo_QueueStateTransitionMessageDeleted.Size(m)
}
func (m *QueueStateTransitionMessageDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueStateTransitionMessageDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_QueueStateTransitionMessageDeleted proto.InternalMessageInfo

func (m *QueueStateTransitionMessageDeleted) GetQueueID() string {
	if m != nil {
		return m.QueueID
	}
	return ""
}

func (m *QueueStateTransitionMessageDeleted) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type QueueStateTransitionMessagePutBatch struct {
	Batches              []*QueueStateTransitionMessagePut `protobuf:"bytes,1,rep,name=batches,proto3" json:"batches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *QueueStateTransitionMessagePutBatch) Reset()         { *m = QueueStateTransitionMessagePutBatch{} }
func (m *QueueStateTransitionMessagePutBatch) String() string { return proto.CompactTextString(m) }
func (*QueueStateTransitionMessagePutBatch) ProtoMessage()    {}
func (*QueueStateTransitionMessagePutBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{23}
}

func (m *QueueStateTransitionMessagePutBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueStateTransitionMessagePutBatch.Unmarshal(m, b)
}
func (m *QueueStateTransitionMessagePutBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueStateTransitionMessagePutBatch.Marshal(b, m, deterministic)
}
func (m *QueueStateTransitionMessagePutBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueStateTransitionMessagePutBatch.Merge(m, src)
}
func (m *QueueStateTransitionMessagePutBatch) XXX_Size() int {
	return xxx_messageInfo_QueueStateTransitionMessagePutBatch.Size(m)
}
func (m *QueueStateTransitionMessagePutBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueStateTransitionMessagePutBatch.DiscardUnknown(m)
}

var xxx_messageInfo_QueueStateTransitionMessagePutBatch proto.InternalMessageInfo

func (m *QueueStateTransitionMessagePutBatch) GetBatches() []*QueueStateTransitionMessagePut {
	if m != nil {
		return m.Batches
	}
	return nil
}

func init() {
	proto.RegisterType((*QueueMetadata)(nil), "pb.QueueMetadata")
	proto.RegisterType((*QueueMetadataList)(nil), "pb.QueueMetadataList")
	proto.RegisterType((*QueueCreateInput)(nil), "pb.QueueCreateInput")
	proto.RegisterType((*QueueCreateOutput)(nil), "pb.QueueCreateOutput")
	proto.RegisterType((*QueueDeleteInput)(nil), "pb.QueueDeleteInput")
	proto.RegisterType((*QueueDeleteOutput)(nil), "pb.QueueDeleteOutput")
	proto.RegisterType((*QueuePutMessageInput)(nil), "pb.QueuePutMessageInput")
	proto.RegisterType((*QueuePutMessageOutput)(nil), "pb.QueuePutMessageOutput")
	proto.RegisterType((*QueuePutMessageBatchInput)(nil), "pb.QueuePutMessageBatchInput")
	proto.RegisterType((*QueuePutMessageBatchOutput)(nil), "pb.QueuePutMessageBatchOutput")
	proto.RegisterType((*QueueGetMessagesInput)(nil), "pb.QueueGetMessagesInput")
	proto.RegisterType((*AckMessageInput)(nil), "pb.AckMessageInput")
	proto.RegisterType((*AckMessageOutput)(nil), "pb.AckMessageOutput")
	proto.RegisterType((*QueueGetMessagesOutput)(nil), "pb.QueueGetMessagesOutput")
	proto.RegisterType((*StreamMessageOutput)(nil), "pb.StreamMessageOutput")
	proto.RegisterType((*QueuesStateTransitionSet)(nil), "pb.QueuesStateTransitionSet")
	proto.RegisterType((*QueuesStateTransition)(nil), "pb.QueuesStateTransition")
	proto.RegisterType((*QueueStateTransitionQueueCreated)(nil), "pb.QueueStateTransitionQueueCreated")
	proto.RegisterType((*QueueStateTransitionQueueDeleted)(nil), "pb.QueueStateTransitionQueueDeleted")
	proto.RegisterType((*QueueStateTransitionMessagePut)(nil), "pb.QueueStateTransitionMessagePut")
	proto.RegisterType((*QueueStateTransitionMessageInflightSet)(nil), "pb.QueueStateTransitionMessageInflightSet")
	proto.RegisterType((*QueueStateTransitionMessageAcked)(nil), "pb.QueueStateTransitionMessageAcked")
	proto.RegisterType((*QueueStateTransitionMessageDeleted)(nil), "pb.QueueStateTransitionMessageDeleted")
	proto.RegisterType((*QueueStateTransitionMessagePutBatch)(nil), "pb.QueueStateTransitionMessagePutBatch")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 821 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0xe3, 0x36,
	0x10, 0x85, 0x1d, 0xc7, 0x76, 0xc6, 0x69, 0x9c, 0x30, 0x37, 0x59, 0x48, 0x03, 0x83, 0x2d, 0x72,
	0x29, 0x10, 0x3b, 0x75, 0x1b, 0x14, 0x45, 0x8b, 0x16, 0x69, 0x8d, 0x76, 0x83, 0x24, 0x6b, 0x87,
	0x0e, 0xf6, 0x61, 0xf7, 0x89, 0x92, 0x99, 0x58, 0xb0, 0x62, 0x69, 0x2d, 0xca, 0xd8, 0x7c, 0xc2,
	0x3e, 0xef, 0x0f, 0xee, 0xa7, 0x2c, 0x4c, 0x52, 0xd7, 0x95, 0x2f, 0x9b, 0x37, 0x71, 0xe6, 0x9c,
	0x33, 0xd4, 0xcc, 0x90, 0x43, 0xa8, 0xf0, 0x67, 0x97, 0x79, 0x0d, 0x77, 0xec, 0x70, 0x07, 0xe5,
	0x5d, 0x43, 0x3f, 0x7f, 0xb4, 0xf8, 0xc0, 0x37, 0x1a, 0xa6, 0xf3, 0xd4, 0x9c, 0x7c, 0x38, 0xb3,
	0xa9, 0xe1, 0x35, 0x9f, 0xde, 0x73, 0x7e, 0x26, 0x20, 0xa6, 0x63, 0x37, 0x5d, 0x6a, 0x0e, 0x19,
	0x6f, 0xba, 0x86, 0x64, 0xe1, 0x3f, 0xe0, 0xbb, 0x3b, 0x9f, 0xf9, 0xec, 0x96, 0x71, 0xda, 0xa7,
	0x9c, 0xa2, 0x0d, 0xc8, 0x5f, 0xb5, 0xb5, 0x5c, 0x3d, 0x77, 0xb2, 0x46, 0xf2, 0x57, 0x6d, 0xa4,
	0x43, 0x79, 0xe2, 0xd8, 0x94, 0x5b, 0x36, 0xd3, 0xf2, 0xf5, 0xdc, 0x49, 0x99, 0x84, 0x6b, 0xfc,
	0x17, 0x6c, 0x25, 0xc8, 0x37, 0x96, 0xc7, 0xd1, 0x29, 0x14, 0x85, 0xd1, 0xd3, 0x72, 0xf5, 0x95,
	0x93, 0x4a, 0x6b, 0xab, 0xe1, 0x1a, 0x8d, 0x04, 0x8c, 0x28, 0x00, 0xc6, 0xb0, 0x29, 0xbe, 0xfe,
	0x1d, 0x33, 0xca, 0xd9, 0xd5, 0xc8, 0xf5, 0xf9, 0x34, 0xbe, 0xd5, 0x0f, 0xe2, 0x5b, 0x7d, 0xbc,
	0xad, 0x62, 0x48, 0x4c, 0xc7, 0xe7, 0xae, 0xcf, 0x43, 0x62, 0x9b, 0xd9, 0x6c, 0x11, 0x51, 0x62,
	0x14, 0xf1, 0x0e, 0x76, 0x84, 0xb1, 0xeb, 0xf3, 0x5b, 0xe6, 0x79, 0xf4, 0x31, 0x9b, 0x8c, 0x4e,
	0xa1, 0xe4, 0xfa, 0x86, 0x6d, 0x79, 0x03, 0xf1, 0xd3, 0x95, 0x56, 0xb5, 0x21, 0x33, 0xd7, 0xe8,
	0x4a, 0x33, 0x09, 0xfc, 0x78, 0x1f, 0x76, 0x53, 0x92, 0x2a, 0x56, 0x07, 0x6a, 0x29, 0xc7, 0x3f,
	0x94, 0x9b, 0x03, 0x19, 0xb0, 0x05, 0x25, 0xb1, 0x0a, 0xd3, 0xa4, 0x85, 0x69, 0x4a, 0xed, 0x8d,
	0x04, 0x40, 0x7c, 0x00, 0x7a, 0x96, 0xa0, 0x0a, 0xf7, 0xb7, 0xda, 0xc7, 0xff, 0x2c, 0xf0, 0x7a,
	0xd9, 0xff, 0xb6, 0x07, 0x45, 0xe7, 0xe1, 0xc1, 0x63, 0x5c, 0xfc, 0x5a, 0x81, 0xa8, 0x15, 0xfe,
	0x1d, 0xaa, 0x97, 0xe6, 0x70, 0x6e, 0x5a, 0x66, 0x51, 0x11, 0x6c, 0x46, 0x54, 0xb5, 0x9f, 0x8f,
	0x39, 0xd8, 0x4b, 0x6f, 0x48, 0xba, 0x96, 0x95, 0x8d, 0x57, 0x61, 0x65, 0x7e, 0x15, 0xd0, 0x01,
	0xac, 0x51, 0x73, 0xd8, 0x91, 0x2a, 0x05, 0xa1, 0x12, 0x19, 0xb0, 0x09, 0xdb, 0x3d, 0x3e, 0x66,
	0xf4, 0x29, 0xb1, 0xc5, 0x58, 0xdc, 0x5c, 0x22, 0xee, 0xaf, 0x50, 0x32, 0x54, 0x71, 0xf2, 0xa2,
	0x38, 0x7a, 0x58, 0x9c, 0xaf, 0x7e, 0x86, 0x04, 0x50, 0x7c, 0x0b, 0x9a, 0xec, 0xeb, 0x1e, 0xa7,
	0x9c, 0xdd, 0x8f, 0xe9, 0xc8, 0xb3, 0xb8, 0xe5, 0x8c, 0x7a, 0x8c, 0xa3, 0x9f, 0xa1, 0xc8, 0x26,
	0x6c, 0xc4, 0x83, 0x6a, 0xd7, 0x42, 0xc1, 0x34, 0x9a, 0x28, 0x20, 0xfe, 0x5c, 0x50, 0x05, 0x4d,
	0x23, 0x10, 0x82, 0xc2, 0xb5, 0x35, 0x0a, 0x12, 0x28, 0xbe, 0xd1, 0x2b, 0x58, 0x8f, 0x1d, 0x93,
	0xbe, 0xea, 0xda, 0x1f, 0xc3, 0x30, 0x29, 0x8d, 0x38, 0x96, 0x24, 0x98, 0xa1, 0x92, 0x3c, 0x37,
	0x7d, 0x95, 0xf9, 0xf9, 0x4a, 0x0a, 0x4b, 0x12, 0x4c, 0x74, 0x03, 0x55, 0x75, 0xee, 0x45, 0xc2,
	0xba, 0xbe, 0xac, 0x4c, 0xa5, 0x85, 0x67, 0x89, 0x45, 0x48, 0x92, 0xa6, 0xa2, 0x77, 0xea, 0xe8,
	0x46, 0x26, 0xd1, 0xfd, 0xda, 0xaa, 0x90, 0x3c, 0x5e, 0x2c, 0x29, 0xe0, 0x24, 0x53, 0x04, 0xbd,
	0x05, 0x14, 0x36, 0xfe, 0x83, 0x6d, 0x3d, 0x0e, 0x78, 0x8f, 0x71, 0xad, 0x28, 0xa4, 0x7f, 0x5a,
	0x20, 0x1d, 0x63, 0x90, 0x0c, 0x15, 0xf4, 0x1a, 0x36, 0x94, 0x35, 0x48, 0x69, 0x49, 0xe8, 0x1e,
	0x2d, 0xd0, 0x0d, 0x92, 0x9a, 0x62, 0x4f, 0x0b, 0xa4, 0x2c, 0x97, 0xe6, 0x90, 0xf5, 0xb5, 0xf2,
	0xfc, 0x02, 0xc5, 0xb1, 0x24, 0xc1, 0xc4, 0xd7, 0x50, 0x5f, 0xd4, 0x1c, 0xe8, 0x18, 0x56, 0xc5,
	0x5d, 0x20, 0xba, 0x2d, 0xf3, 0x36, 0x97, 0x7e, 0xdc, 0x9a, 0x23, 0x16, 0x6c, 0x3d, 0x35, 0x5c,
	0xb0, 0x0d, 0x87, 0xf3, 0x6b, 0x86, 0x34, 0x28, 0x09, 0x44, 0x48, 0x0b, 0x96, 0xd3, 0xc3, 0xdb,
	0x49, 0x5c, 0x1a, 0x72, 0x35, 0x65, 0x74, 0xe9, 0xb3, 0xed, 0x50, 0xd9, 0xba, 0xeb, 0x24, 0x58,
	0xe2, 0x09, 0x1c, 0x2d, 0x57, 0xc6, 0x17, 0x44, 0xd5, 0xa1, 0xdc, 0x66, 0xb4, 0x6f, 0x5b, 0x23,
	0x26, 0xc2, 0x16, 0x48, 0xb8, 0xc6, 0xf7, 0xd9, 0x99, 0x89, 0x97, 0xe2, 0xdb, 0x23, 0xe2, 0x37,
	0x80, 0x17, 0x37, 0xcf, 0x0b, 0x74, 0x4d, 0xf8, 0x61, 0x89, 0x73, 0x84, 0xfe, 0x8c, 0xee, 0x48,
	0x79, 0xa5, 0x2d, 0x73, 0xa8, 0x03, 0x4a, 0xeb, 0xd3, 0x8a, 0x7a, 0x77, 0x78, 0x3d, 0x36, 0x9e,
	0x58, 0x26, 0x43, 0x17, 0x50, 0x94, 0x2d, 0x87, 0x76, 0x42, 0xa1, 0xd8, 0xbb, 0x40, 0xdf, 0x4d,
	0x59, 0xd5, 0x15, 0x7e, 0x01, 0x45, 0xf9, 0xab, 0x31, 0x5a, 0xec, 0x55, 0x10, 0xa3, 0xc5, 0xdf,
	0x01, 0xe8, 0x12, 0x20, 0x9a, 0xa2, 0x68, 0xe6, 0xec, 0xd5, 0x6b, 0x19, 0x1e, 0x25, 0xd1, 0x85,
	0x6a, 0x6a, 0x10, 0xa3, 0xef, 0x33, 0xd0, 0xd1, 0xcc, 0xd7, 0x0f, 0x67, 0xb9, 0x95, 0xe2, 0x6f,
	0x00, 0xd1, 0x14, 0x45, 0xdb, 0x53, 0x74, 0x6a, 0x20, 0xeb, 0x3b, 0x49, 0xa3, 0x22, 0xfe, 0x07,
	0x1b, 0x89, 0xf1, 0xe6, 0xa1, 0x5a, 0xd6, 0xc0, 0x92, 0x12, 0xfb, 0x53, 0x57, 0xc6, 0x34, 0x3c,
	0xcf, 0x19, 0x45, 0xf1, 0x26, 0xfc, 0xe5, 0x4b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x71, 0x11, 0xc9,
	0xe8, 0x58, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueuesServiceClient is the client API for QueuesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueuesServiceClient interface {
	Create(ctx context.Context, in *QueueCreateInput, opts ...grpc.CallOption) (*QueueCreateOutput, error)
	Delete(ctx context.Context, in *QueueDeleteInput, opts ...grpc.CallOption) (*QueueDeleteOutput, error)
	PutMessage(ctx context.Context, in *QueuePutMessageInput, opts ...grpc.CallOption) (*QueuePutMessageOutput, error)
	PutMessageBatch(ctx context.Context, in *QueuePutMessageBatchInput, opts ...grpc.CallOption) (*QueuePutMessageBatchOutput, error)
	AckMessage(ctx context.Context, in *AckMessageInput, opts ...grpc.CallOption) (*AckMessageOutput, error)
	StreamMessages(ctx context.Context, in *QueueGetMessagesInput, opts ...grpc.CallOption) (QueuesService_StreamMessagesClient, error)
}

type queuesServiceClient struct {
	cc *grpc.ClientConn
}

func NewQueuesServiceClient(cc *grpc.ClientConn) QueuesServiceClient {
	return &queuesServiceClient{cc}
}

func (c *queuesServiceClient) Create(ctx context.Context, in *QueueCreateInput, opts ...grpc.CallOption) (*QueueCreateOutput, error) {
	out := new(QueueCreateOutput)
	err := c.cc.Invoke(ctx, "/pb.QueuesService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queuesServiceClient) Delete(ctx context.Context, in *QueueDeleteInput, opts ...grpc.CallOption) (*QueueDeleteOutput, error) {
	out := new(QueueDeleteOutput)
	err := c.cc.Invoke(ctx, "/pb.QueuesService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queuesServiceClient) PutMessage(ctx context.Context, in *QueuePutMessageInput, opts ...grpc.CallOption) (*QueuePutMessageOutput, error) {
	out := new(QueuePutMessageOutput)
	err := c.cc.Invoke(ctx, "/pb.QueuesService/PutMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queuesServiceClient) PutMessageBatch(ctx context.Context, in *QueuePutMessageBatchInput, opts ...grpc.CallOption) (*QueuePutMessageBatchOutput, error) {
	out := new(QueuePutMessageBatchOutput)
	err := c.cc.Invoke(ctx, "/pb.QueuesService/PutMessageBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queuesServiceClient) AckMessage(ctx context.Context, in *AckMessageInput, opts ...grpc.CallOption) (*AckMessageOutput, error) {
	out := new(AckMessageOutput)
	err := c.cc.Invoke(ctx, "/pb.QueuesService/AckMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queuesServiceClient) StreamMessages(ctx context.Context, in *QueueGetMessagesInput, opts ...grpc.CallOption) (QueuesService_StreamMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_QueuesService_serviceDesc.Streams[0], "/pb.QueuesService/StreamMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &queuesServiceStreamMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QueuesService_StreamMessagesClient interface {
	Recv() (*StreamMessageOutput, error)
	grpc.ClientStream
}

type queuesServiceStreamMessagesClient struct {
	grpc.ClientStream
}

func (x *queuesServiceStreamMessagesClient) Recv() (*StreamMessageOutput, error) {
	m := new(StreamMessageOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// QueuesServiceServer is the server API for QueuesService service.
type QueuesServiceServer interface {
	Create(context.Context, *QueueCreateInput) (*QueueCreateOutput, error)
	Delete(context.Context, *QueueDeleteInput) (*QueueDeleteOutput, error)
	PutMessage(context.Context, *QueuePutMessageInput) (*QueuePutMessageOutput, error)
	PutMessageBatch(context.Context, *QueuePutMessageBatchInput) (*QueuePutMessageBatchOutput, error)
	AckMessage(context.Context, *AckMessageInput) (*AckMessageOutput, error)
	StreamMessages(*QueueGetMessagesInput, QueuesService_StreamMessagesServer) error
}

// UnimplementedQueuesServiceServer can be embedded to have forward compatible implementations.
type UnimplementedQueuesServiceServer struct {
}

func (*UnimplementedQueuesServiceServer) Create(ctx context.Context, req *QueueCreateInput) (*QueueCreateOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedQueuesServiceServer) Delete(ctx context.Context, req *QueueDeleteInput) (*QueueDeleteOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedQueuesServiceServer) PutMessage(ctx context.Context, req *QueuePutMessageInput) (*QueuePutMessageOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMessage not implemented")
}
func (*UnimplementedQueuesServiceServer) PutMessageBatch(ctx context.Context, req *QueuePutMessageBatchInput) (*QueuePutMessageBatchOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMessageBatch not implemented")
}
func (*UnimplementedQueuesServiceServer) AckMessage(ctx context.Context, req *AckMessageInput) (*AckMessageOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckMessage not implemented")
}
func (*UnimplementedQueuesServiceServer) StreamMessages(req *QueueGetMessagesInput, srv QueuesService_StreamMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMessages not implemented")
}

func RegisterQueuesServiceServer(s *grpc.Server, srv QueuesServiceServer) {
	s.RegisterService(&_QueuesService_serviceDesc, srv)
}

func _QueuesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueCreateInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QueuesService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesServiceServer).Create(ctx, req.(*QueueCreateInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueuesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueDeleteInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QueuesService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesServiceServer).Delete(ctx, req.(*QueueDeleteInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueuesService_PutMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueuePutMessageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesServiceServer).PutMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QueuesService/PutMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesServiceServer).PutMessage(ctx, req.(*QueuePutMessageInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueuesService_PutMessageBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueuePutMessageBatchInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesServiceServer).PutMessageBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QueuesService/PutMessageBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesServiceServer).PutMessageBatch(ctx, req.(*QueuePutMessageBatchInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueuesService_AckMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckMessageInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesServiceServer).AckMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.QueuesService/AckMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesServiceServer).AckMessage(ctx, req.(*AckMessageInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueuesService_StreamMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueueGetMessagesInput)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueuesServiceServer).StreamMessages(m, &queuesServiceStreamMessagesServer{stream})
}

type QueuesService_StreamMessagesServer interface {
	Send(*StreamMessageOutput) error
	grpc.ServerStream
}

type queuesServiceStreamMessagesServer struct {
	grpc.ServerStream
}

func (x *queuesServiceStreamMessagesServer) Send(m *StreamMessageOutput) error {
	return x.ServerStream.SendMsg(m)
}

var _QueuesService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.QueuesService",
	HandlerType: (*QueuesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _QueuesService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _QueuesService_Delete_Handler,
		},
		{
			MethodName: "PutMessage",
			Handler:    _QueuesService_PutMessage_Handler,
		},
		{
			MethodName: "PutMessageBatch",
			Handler:    _QueuesService_PutMessageBatch_Handler,
		},
		{
			MethodName: "AckMessage",
			Handler:    _QueuesService_AckMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMessages",
			Handler:       _QueuesService_StreamMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "types.proto",
}
