// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package peers is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	Metadata
	ComputeUsage
	MemoryUsage
	PeerMetadataList
*/
package peers

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Metadata struct {
	ID           string        `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	MeshID       string        `protobuf:"bytes,2,opt,name=MeshID" json:"MeshID,omitempty"`
	Hostname     string        `protobuf:"bytes,3,opt,name=Hostname" json:"Hostname,omitempty"`
	Address      string        `protobuf:"bytes,4,opt,name=Address" json:"Address,omitempty"`
	LastAdded    int64         `protobuf:"varint,5,opt,name=LastAdded" json:"LastAdded,omitempty"`
	LastDeleted  int64         `protobuf:"varint,6,opt,name=LastDeleted" json:"LastDeleted,omitempty"`
	MemoryUsage  *MemoryUsage  `protobuf:"bytes,7,opt,name=MemoryUsage" json:"MemoryUsage,omitempty"`
	ComputeUsage *ComputeUsage `protobuf:"bytes,8,opt,name=ComputeUsage" json:"ComputeUsage,omitempty"`
	Runtime      string        `protobuf:"bytes,9,opt,name=Runtime" json:"Runtime,omitempty"`
	Services     []string      `protobuf:"bytes,10,rep,name=Services" json:"Services,omitempty"`
	Started      int64         `protobuf:"varint,11,opt,name=Started" json:"Started,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Metadata) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Metadata) GetMeshID() string {
	if m != nil {
		return m.MeshID
	}
	return ""
}

func (m *Metadata) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Metadata) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Metadata) GetLastAdded() int64 {
	if m != nil {
		return m.LastAdded
	}
	return 0
}

func (m *Metadata) GetLastDeleted() int64 {
	if m != nil {
		return m.LastDeleted
	}
	return 0
}

func (m *Metadata) GetMemoryUsage() *MemoryUsage {
	if m != nil {
		return m.MemoryUsage
	}
	return nil
}

func (m *Metadata) GetComputeUsage() *ComputeUsage {
	if m != nil {
		return m.ComputeUsage
	}
	return nil
}

func (m *Metadata) GetRuntime() string {
	if m != nil {
		return m.Runtime
	}
	return ""
}

func (m *Metadata) GetServices() []string {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Metadata) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

type ComputeUsage struct {
	Cores      int64 `protobuf:"varint,1,opt,name=Cores" json:"Cores,omitempty"`
	Goroutines int64 `protobuf:"varint,2,opt,name=Goroutines" json:"Goroutines,omitempty"`
}

func (m *ComputeUsage) Reset()                    { *m = ComputeUsage{} }
func (m *ComputeUsage) String() string            { return proto.CompactTextString(m) }
func (*ComputeUsage) ProtoMessage()               {}
func (*ComputeUsage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ComputeUsage) GetCores() int64 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *ComputeUsage) GetGoroutines() int64 {
	if m != nil {
		return m.Goroutines
	}
	return 0
}

type MemoryUsage struct {
	Alloc      uint64 `protobuf:"varint,1,opt,name=Alloc" json:"Alloc,omitempty"`
	TotalAlloc uint64 `protobuf:"varint,2,opt,name=TotalAlloc" json:"TotalAlloc,omitempty"`
	Sys        uint64 `protobuf:"varint,3,opt,name=Sys" json:"Sys,omitempty"`
	NumGC      uint32 `protobuf:"varint,4,opt,name=NumGC" json:"NumGC,omitempty"`
}

func (m *MemoryUsage) Reset()                    { *m = MemoryUsage{} }
func (m *MemoryUsage) String() string            { return proto.CompactTextString(m) }
func (*MemoryUsage) ProtoMessage()               {}
func (*MemoryUsage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MemoryUsage) GetAlloc() uint64 {
	if m != nil {
		return m.Alloc
	}
	return 0
}

func (m *MemoryUsage) GetTotalAlloc() uint64 {
	if m != nil {
		return m.TotalAlloc
	}
	return 0
}

func (m *MemoryUsage) GetSys() uint64 {
	if m != nil {
		return m.Sys
	}
	return 0
}

func (m *MemoryUsage) GetNumGC() uint32 {
	if m != nil {
		return m.NumGC
	}
	return 0
}

type PeerMetadataList struct {
	Metadatas []*Metadata `protobuf:"bytes,1,rep,name=Metadatas" json:"Metadatas,omitempty"`
}

func (m *PeerMetadataList) Reset()                    { *m = PeerMetadataList{} }
func (m *PeerMetadataList) String() string            { return proto.CompactTextString(m) }
func (*PeerMetadataList) ProtoMessage()               {}
func (*PeerMetadataList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PeerMetadataList) GetMetadatas() []*Metadata {
	if m != nil {
		return m.Metadatas
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "peers.Metadata")
	proto.RegisterType((*ComputeUsage)(nil), "peers.ComputeUsage")
	proto.RegisterType((*MemoryUsage)(nil), "peers.MemoryUsage")
	proto.RegisterType((*PeerMetadataList)(nil), "peers.PeerMetadataList")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xdd, 0x4a, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0xd2, 0xbf, 0x4c, 0xfc, 0x29, 0xab, 0xc8, 0x22, 0x22, 0x21, 0x57, 0xb9, 0xb1,
	0x17, 0x55, 0xf0, 0x3a, 0x34, 0x50, 0x0b, 0xad, 0xc8, 0x56, 0x1f, 0x60, 0x6d, 0x06, 0x0d, 0x26,
	0xdd, 0xb0, 0xbb, 0x11, 0xfa, 0xc4, 0xbe, 0x86, 0xec, 0xa6, 0x69, 0xd3, 0xbb, 0x7c, 0xe7, 0xcc,
	0x0c, 0x39, 0x33, 0x0b, 0x81, 0xde, 0x55, 0xa8, 0x26, 0x95, 0x14, 0x5a, 0x90, 0x7e, 0x85, 0x28,
	0x55, 0xf4, 0xe7, 0xc2, 0x68, 0x85, 0x9a, 0x67, 0x5c, 0x73, 0x72, 0x01, 0xee, 0x22, 0xa5, 0x4e,
	0xe8, 0xc4, 0x3e, 0x73, 0x17, 0x29, 0xb9, 0x81, 0xc1, 0x0a, 0xd5, 0xf7, 0x22, 0xa5, 0xae, 0xd5,
	0xf6, 0x44, 0x6e, 0x61, 0xf4, 0x22, 0x94, 0xde, 0xf2, 0x12, 0xa9, 0x67, 0x9d, 0x03, 0x13, 0x0a,
	0xc3, 0x24, 0xcb, 0x24, 0x2a, 0x45, 0x7b, 0xd6, 0x6a, 0x91, 0xdc, 0x81, 0xbf, 0xe4, 0x4a, 0x27,
	0x59, 0x86, 0x19, 0xed, 0x87, 0x4e, 0xec, 0xb1, 0xa3, 0x40, 0x42, 0x08, 0x0c, 0xa4, 0x58, 0xa0,
	0xc6, 0x8c, 0x0e, 0xac, 0xdf, 0x95, 0xc8, 0x13, 0x04, 0x2b, 0x2c, 0x85, 0xdc, 0x7d, 0x28, 0xfe,
	0x85, 0x74, 0x18, 0x3a, 0x71, 0x30, 0x25, 0x13, 0x9b, 0x63, 0xd2, 0x71, 0x58, 0xb7, 0x8c, 0x3c,
	0xc3, 0xd9, 0x4c, 0x94, 0x55, 0xad, 0xb1, 0x69, 0x1b, 0xd9, 0xb6, 0xab, 0x7d, 0x5b, 0xd7, 0x62,
	0x27, 0x85, 0x26, 0x08, 0xab, 0xb7, 0x3a, 0x2f, 0x91, 0xfa, 0x4d, 0x90, 0x3d, 0x9a, 0xf8, 0x6b,
	0x94, 0xbf, 0xf9, 0x06, 0x15, 0x85, 0xd0, 0x33, 0xf1, 0x5b, 0x36, 0x5d, 0x6b, 0xcd, 0xa5, 0x89,
	0x10, 0xd8, 0x08, 0x2d, 0x46, 0xe9, 0xe9, 0x8f, 0x90, 0x6b, 0xe8, 0xcf, 0x84, 0x44, 0x65, 0xf7,
	0xed, 0xb1, 0x06, 0xc8, 0x3d, 0xc0, 0x5c, 0x48, 0x51, 0xeb, 0x7c, 0x8b, 0xca, 0xae, 0xdd, 0x63,
	0x1d, 0x25, 0xfa, 0x39, 0x59, 0x82, 0x19, 0x92, 0x14, 0x85, 0xd8, 0xd8, 0x21, 0x3d, 0xd6, 0x80,
	0x19, 0xf2, 0x2e, 0x34, 0x2f, 0x1a, 0xcb, 0xb5, 0x56, 0x47, 0x21, 0x63, 0xf0, 0xd6, 0x3b, 0x65,
	0x4f, 0xd7, 0x63, 0xe6, 0xd3, 0xcc, 0x79, 0xad, 0xcb, 0xf9, 0xcc, 0xde, 0xec, 0x9c, 0x35, 0x10,
	0x25, 0x30, 0x7e, 0x43, 0x94, 0xed, 0xfb, 0x58, 0xe6, 0x4a, 0x93, 0x07, 0xf0, 0x5b, 0x36, 0xbf,
	0xee, 0xc5, 0xc1, 0xf4, 0xf2, 0x70, 0x83, 0x46, 0x67, 0xc7, 0x8a, 0xcf, 0x81, 0x7d, 0x6d, 0x8f,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x71, 0x1a, 0x95, 0x7c, 0x02, 0x00, 0x00,
}
