// Code generated by protoc-gen-go. DO NOT EDIT.
// source: events.proto

/*
Package broker is a generated protocol buffer package.

It is generated from these files:
	events.proto

It has these top-level messages:
	MessagePublished
*/
package broker

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessagePublished struct {
	Recipient []string `protobuf:"bytes,1,rep,name=Recipient" json:"Recipient,omitempty"`
	Topic     []byte   `protobuf:"bytes,2,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Qos       []int32  `protobuf:"varint,3,rep,packed,name=Qos" json:"Qos,omitempty"`
	Payload   []byte   `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	Retained  bool     `protobuf:"varint,5,opt,name=Retained" json:"Retained,omitempty"`
	Dup       bool     `protobuf:"varint,6,opt,name=Dup" json:"Dup,omitempty"`
}

func (m *MessagePublished) Reset()                    { *m = MessagePublished{} }
func (m *MessagePublished) String() string            { return proto.CompactTextString(m) }
func (*MessagePublished) ProtoMessage()               {}
func (*MessagePublished) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MessagePublished) GetRecipient() []string {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *MessagePublished) GetTopic() []byte {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *MessagePublished) GetQos() []int32 {
	if m != nil {
		return m.Qos
	}
	return nil
}

func (m *MessagePublished) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MessagePublished) GetRetained() bool {
	if m != nil {
		return m.Retained
	}
	return false
}

func (m *MessagePublished) GetDup() bool {
	if m != nil {
		return m.Dup
	}
	return false
}

func init() {
	proto.RegisterType((*MessagePublished)(nil), "broker.MessagePublished")
}

func init() { proto.RegisterFile("events.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x86, 0x89, 0xb1, 0xb5, 0x3d, 0x3a, 0x94, 0xe0, 0x70, 0x88, 0x43, 0x70, 0xca, 0xe4, 0xe2,
	0x2b, 0xb8, 0x0a, 0x35, 0xf8, 0x02, 0x69, 0x7b, 0x68, 0xb0, 0x34, 0xa1, 0x49, 0x05, 0xdf, 0xc6,
	0x47, 0x95, 0x56, 0xd4, 0xed, 0xfb, 0x3e, 0x8e, 0xe3, 0x87, 0x82, 0x1e, 0xd4, 0xc7, 0xb0, 0xf7,
	0x83, 0x8b, 0x4e, 0xa4, 0xf5, 0xe0, 0xee, 0x34, 0xec, 0x5e, 0x0c, 0xca, 0x13, 0x85, 0x60, 0xae,
	0x54, 0x8d, 0x75, 0x67, 0xc3, 0x8d, 0x5a, 0xb1, 0x85, 0x5c, 0x53, 0x63, 0xbd, 0xa5, 0x3e, 0x22,
	0x93, 0x5c, 0xe5, 0xfa, 0x1f, 0xc4, 0x1a, 0x92, 0x8b, 0xf3, 0xb6, 0xc1, 0x85, 0x64, 0xaa, 0xd0,
	0x1f, 0x11, 0x25, 0xf0, 0xb3, 0x0b, 0xc8, 0x25, 0x57, 0x89, 0x9e, 0x50, 0x20, 0xac, 0x2a, 0xf3,
	0xec, 0x9c, 0x69, 0x71, 0x39, 0x5f, 0x7e, 0x55, 0x6c, 0x20, 0xd3, 0x14, 0x8d, 0xed, 0xa9, 0xc5,
	0x44, 0x32, 0x95, 0xe9, 0x9f, 0x4f, 0x7f, 0x8e, 0xa3, 0xc7, 0x74, 0xce, 0x13, 0xd6, 0xe9, 0xbc,
	0xf8, 0xf0, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xba, 0xcb, 0x29, 0xa1, 0xc1, 0x00, 0x00, 0x00,
}
